// ══════════════════════════════════════
// 해피콜 스크립트 - Google Apps Script (데이터 API 전용)
// ══════════════════════════════════════
// 화면(HTML)은 GitHub Pages에서 서빙하고,
// 이 스크립트는 구글시트 데이터를 읽고 쓰는 API 역할만 합니다.
//
// 설정: 시트 > 확장 프로그램 > Apps Script
//  1. Code.gs 내용을 이 파일로 교체 (Index.html 파일은 삭제해도 됨)
//  2. 배포 > 새 배포 > 웹앱 > 실행계정:나 > 액세스:모든사용자
//  3. 배포된 웹앱 URL을 index.html의 SHEET_API_URL에 붙여넣기
//  ※ 재배포시 "배포 관리 > 버전 업데이트"를 쓰면 URL이 유지됩니다
// ══════════════════════════════════════

const SHEET_NAME = '스크립트';

// GET: 전체 스크립트 데이터를 JSON으로 반환 (GitHub Pages HTML이 불러갈 때 사용)
function doGet() {
  return ContentService
    .createTextOutput(loadScripts())
    .setMimeType(ContentService.MimeType.JSON);
}

// POST: 전체 스크립트 데이터를 받아 시트에 저장
function doPost(e) {
  try {
    saveScripts(e.postData.contents);
    return ContentService
      .createTextOutput(JSON.stringify({ok: true}))
      .setMimeType(ContentService.MimeType.JSON);
  } catch(err) {
    return ContentService
      .createTextOutput(JSON.stringify({ok: false, error: String(err)}))
      .setMimeType(ContentService.MimeType.JSON);
  }
}

function loadScripts() {
  try {
    const sheet = getOrCreateSheet();
    const lastRow = sheet.getLastRow();
    if (lastRow < 2) {
      const defaults = getDefaultData();
      saveScripts(JSON.stringify(defaults));
      return JSON.stringify(defaults);
    }
    const data = sheet.getRange(2, 1, lastRow - 1, 9).getValues();
    const scripts = data.filter(row => row[0]).map(row => ({
      id: String(row[0]), carrier: String(row[1]), section: String(row[2]),
      subsection: row[3] ? String(row[3]) : null,
      ownerTypes: parseOwnerTypes(String(row[4])),
      order: Number(row[5]) || 1,
      cctvType: row[6] ? String(row[6]) : null,
      script: String(row[7] || ''),
      note: row[8] ? String(row[8]) : null,
    }));
    return JSON.stringify(scripts);
  } catch(e) { throw new Error('불러오기 실패: ' + e.message); }
}

function saveScripts(jsonStr) {
  try {
    const scripts = JSON.parse(jsonStr);
    if (!Array.isArray(scripts)) throw new Error('잘못된 데이터');
    const sheet = getOrCreateSheet();
    const lastRow = sheet.getLastRow();
    if (lastRow > 1) sheet.getRange(2, 1, lastRow - 1, 9).clearContent();
    if (scripts.length === 0) return;
    const rows = scripts.filter(s => s && s.id).map(s => [
      s.id||'', s.carrier||'', s.section||'', s.subsection||'',
      formatOwnerTypes(s.ownerTypes), s.order||1, s.cctvType||'',
      s.script||'', s.note||''
    ]);
    sheet.getRange(2, 1, rows.length, 9).setValues(rows);
  } catch(e) { throw new Error('저장 실패: ' + e.message); }
}

function getOrCreateSheet() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  let sheet = ss.getSheetByName(SHEET_NAME);
  if (!sheet) {
    sheet = ss.insertSheet(SHEET_NAME);
    const headers = ['ID','통신사','섹션','서브섹션','명의자유형','순서','CCTV유형','스크립트','비고'];
    sheet.getRange(1,1,1,headers.length).setValues([headers]);
    const h = sheet.getRange(1,1,1,headers.length);
    h.setBackground('#2563eb'); h.setFontColor('#ffffff'); h.setFontWeight('bold');
    sheet.setFrozenRows(1);
    [90,80,130,130,100,45,80,520,320].forEach((w,i) => sheet.setColumnWidth(i+1,w));
  }
  return sheet;
}

function parseOwnerTypes(val) {
  if (!val || val.trim() === 'all') return 'all';
  const parts = val.split(',').map(s => s.trim()).filter(Boolean);
  return (parts.length === 1 && parts[0] === 'all') ? 'all' : parts;
}

function formatOwnerTypes(val) {
  if (!val || val === 'all') return 'all';
  if (Array.isArray(val)) return val.join(',');
  return String(val);
}

function getDefaultData() {
  return [
{id:"kt001",carrier:"KT",section:"녹취통보",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"안녕하세요 인터넷 접수 받은곳인데요 계약내용에 대한 해피콜 안내 진행하겠습니다.",note:null},
{id:"kt002",carrier:"KT",section:"명의자 정보",subsection:"일반",ownerTypes:["일반"],order:1,cctvType:null,script:"XXX님, 명의자 본인 되시구요? (네)\n실명확인차 주민번호 앞자리 6자리 확인 부탁드립니다 (고객님이 불러주셔야됨)\n고객님 성별이 남자or여자분 맞으시죠? (네)",note:null},
{id:"kt003",carrier:"KT",section:"명의자 정보",subsection:"법인/개인사업자",ownerTypes:["법인사업자"],order:1,cctvType:null,script:"(대표자와 녹취) 대표자 000님 본인되시죠? (네)\n(직원과 녹취) 직원이신 000님 본인되시죠? (네)\n\"상호명 00000\", 사업자번호 000-00-00000 명의로 신청하셨죠? (네)",note:null},
{id:"kt004",carrier:"KT",section:"명의자 정보",subsection:"법정대리인",ownerTypes:["법정대리인"],order:1,cctvType:null,script:"명의자는 000님 주민번호 앞자리가 000000 남자or여자분 이구요\n통화하시는 고객님은 법정대리인인 000님 주민번호 앞자리가 000000 이시고, 남자or여자분 맞으시죠? (네)",note:"미성년자 추가내용 (법정대리인, 미성년자 둘다 해피콜 해야함)\n인터넷 가입사항의 모든걸 법정대리인 누구에게 위임하는게 맞으시죠?"},
{id:"kt005",carrier:"KT",section:"명의자 정보",subsection:"비대면 안내",ownerTypes:["법정대리인"],order:1,cctvType:null,script:"본 계약은 비대면 진행으로 가입에 대한 내용은 해피콜로 계약증빙되니 참고 부탁드립니다.",note:"뭐냐고 하면: 해피콜이 가입에 대한 증빙이라고 보시면 되세요"},
{id:"kt006",carrier:"KT",section:"상품공통",subsection:"공통",ownerTypes:"all",order:1,cctvType:null,script:"신청하신 상품의 총 요금은 월 000원이며 모두 3년 약정입니다.\n사은품은 00상품권 00만원, 현금사은품은 00만원이고 설치비 00원은 다음달에 청구됩니다.\n야간·주말·공휴일 설치시 할증 발생하니 참고 부탁드립니다. (야간 = 평일 9시~18시 그외 시간)\n휴대폰 결합을 원하시면 설치후 다음날 고객센터에 할인 금액, 조건 확인하시고 직접 신청해 주시면 됩니다.\n현금사은품은 19시 전후로 입금 되십니다.",note:null},
{id:"kt007",carrier:"KT",section:"상품-인터넷",subsection:"인터넷",ownerTypes:"all",order:1,cctvType:null,script:"가입하신 인터넷은 최소 00M 속도까지 보장되며 PC는 2대까지 사용 가능합니다.\n(200M/500M/1G) 이전설치시 기가급이 설치 불가하면 100M상품으로라도 계속 이용해 주셔야 하며 일일사용량 최소 150G 초과시 당일에 한해 100M 속도로 제한됩니다.",note:"100M인터넷 = ftth(50메가), xdsl(2메가) / 500M인터넷 = 250메가\n1G = 500메가 / QOS 초과시 당일 밤 12시까지 100Mbps 속도로 제한됨"},
{id:"kt008",carrier:"KT",section:"상품-TV",subsection:"TV",ownerTypes:"all",order:1,cctvType:null,script:"기가지니 상품은 3년 약정이며, 개통후 약정내 다른상품으로 변경하시거나 해지시 할인받으셨던 금액이 위약금으로 청구될수 있습니다.",note:null},
{id:"kt009",carrier:"KT",section:"상품-인터넷전화",subsection:"인터넷전화",ownerTypes:"all",order:1,cctvType:null,script:"인터넷전화 단말기 금액은 0000원이고 요금제 3년 약정으로 단말기금액과 월 이용료 oo원 이며, 약정만료 이전에 요금제 변경 해지 시 할인금액이 위약금으로 청구됩니다.",note:"*AT05-704V / 단말금액 88,000원(월 2,450원) / 월 총이용료 6,300원"},
{id:"kt010",carrier:"KT",section:"상품-번호이동",subsection:"번호이동",ownerTypes:"all",order:1,cctvType:null,script:"지금 사용중인 전화는 번호이동이 끝날때 까지 해지나 정지 하시면 안되니 참고하세요.",note:null},
{id:"kt011",carrier:"KT",section:"상품-집전화",subsection:"집전화",ownerTypes:"all",order:1,cctvType:null,script:"일반전화 요금제 3년약정으로 월요금은 0000원입니다. 약정만료 이전에 요금제 변경 해지 시 할인금액이 위약금으로 청구됩니다.\n(신규) 전화번호는 설치가 완료 되어야 확정됩니다.",note:"*월요금 6,050원"},
{id:"kt_usim",carrier:"KT",section:"상품-유심동판",subsection:"유심동판",ownerTypes:"all",order:99,cctvType:null,script:"가입하신 KT휴대폰 00요금제 약정 0년이시고, 0년이내 해지·번호이동·기기변경시 위약금 발생되시구요~\n개통후 단순변심으로인한 취소는 불가하시고, 휴대폰 요금제는 6개월이후 하향가능하시지만\n분실정지·일시정지·미납정지·해지 또는 비정상사용·유심변경·기기변경·가개통·명의변경은 10개월간 불가하시구요.\n10개월이내에는 결합해지도 하시면 안되시고, 안내드린 내용중 한가지라도 위배사항 발생시 지원금 전액환수되시니 주의 부탁드리구요.\n§※ 판매점용 해피콜/ 유심동판 = 인터넷과 함께 KT휴대폰도 동시에 접수된 경우에만 해당",note:null},
{id:"kt012",carrier:"KT",section:"위약금·환수",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"본계약은 3년 약정 상품으로 약정내 해지시 위약금이 청구 되시며 만 12개월(3사공통) 이내 한가지 상품이라도 개통 당일이나 중도 해지 셋탑 또는 요금제 변경, 결합해지, 복지등록, 해지, 연체, 정지, 명의이전, 패밀리 결합, 교육청 할인, \"KT 따로살아도 가족결합\" 등 기타 할인프로그램 등록, 기업용 상품과 결합 또는 전환, 본사 프로모션 참여시 위약금 발생할 수 있고 사은품까지 전액 반환되니 유의 부탁드리구요\n\n★특히 TV 상품은 어떠한 사유로도 만 9개월 이내 하향시 사은품 환수되며, 가장 낮은채널로 하향시 사은품은 전액 환수되기 때문에 만 9개월 이후에 하향 부탁드립니다.★",note:null},
{id:"kt013",carrier:"KT",section:"클레임 방어",subsection:"물류사은품",ownerTypes:"all",order:91,cctvType:null,script:"(물류사은품) 물류사은품은 수령 이후에는 반송이 불가능하기 때문에 현금으로 반환해 주시면 됩니다.\n초기 불량 확인 전까지 A/S 신청을 위해 제품박스를 버리지 말아주시고, 사은품 불량 사유는 인터넷 해지 사유가 되지 않습니다.",note:"TV상품별 위약금 - 상품권 금액 - 고객 현금부담금액 + 현금사은품 = 물류사은품 위약금"},
{id:"kt014",carrier:"KT",section:"개인정보 활용동의",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"서비스제공 등을 위하여 신청인의 성명, 주민번호, 이용시간 및 요금납부자의 성명, 생년월일 등 개인정보를 수집하고 신용정보를 조회하여 가입기간 동안 이용하며 해지후 6개월까지 보유하는데 동의하십니까? (네)\n약정기간 만료, 요금감면 행사 등 마케팅 활용에 동의 하시나요? (네)/(아니요) (Yes를 유도해주세요)",note:"은행권 신용정보가 아니구요 단순 연체 조회입니다~\n동의 하지 않으시면 서비스 제공이 어려우니 동의 부탁드려요\n마케팅 활용 동의 거부시 이름뒤에 (거부)로 기재해주세요\n\n[해지후 6개월 보유 참고]\n해지 당월 요금은 다음달에 청구해야 하기 때문에 최소 1개월 이상 보관이 필요합니다. 만약 미납이 생기면 그 다음달에도 청구, 또 미납되면 또 그다음달... 이런 식으로 해지후 요금청구에 필요해서 ★최대★ 6개월 보유입니다!\n(예: 4월 해지 → 5월에 요금청구, 미납 시 6월·7월... 최대 10월까지 보유 가능)"},
{id:"kt017",carrier:"KT",section:"클레임 방어",subsection:"기존고객·소개비",ownerTypes:"all",order:1,cctvType:null,script:"기존에 사용하시던 상품은 자동해지 되지 않으니 직접 해지하셔야합니다.\n신청하신 상품 신규 개통일 기준으로 설치 장소, 사용명의와 관계없이 설치 전 해지한 KT 회선이 확인될 경우 또는 설치 후 1년 이내 해지, 정지가 확인될 경우 신규로 개통 받으신 사은품 전액 반환될 수 있으며 본사 소명차 추가서류 확인이 필요할수있으니 참고해주세요.\n(소개비) 소개시 1명당 6만원 입금해드리고 있으니 많은 소개 부탁드립니다.(판매점X)\n(설치전) 사유무관하게 00일까지 설치와 결합이 되지 않으면 사은품이 지급되지 않습니다.\n(설치전) 설치 전 상품 변경시 사은품 변동될 수 있으니 변경희망 시 꼭 저희한테 연락주셔야 하구요.\n(주소증빙시) 현금사은품은 개통 후 저희쪽으로 연락주시고 주소증빙이 완료되면 입금됩니다.",note:"각 거래처별로 00일까지 설치, 결합이 완료되지 않으면 다음달 사은품으로 재접수 해야함"},
{id:"kt019",carrier:"KT",section:"클레임 방어",subsection:"원스톱 해지",ownerTypes:"all",order:3,cctvType:null,script:"(원스톱해지 가입고객) 원스톱 해지신청으로 해지가능한 기존통신사의 상품은 인터넷과 TV상품에 한하며, 이외 사용하시던 기존상품들은 고객님께서 별도로 해지해주셔야 합니다.\n최초 신청시 정해진 개통일정에서 임의로 설치일정 변경, 기타사유로 인한 설치지연 등으로 설치일정이 변경될 경우 기존 이용하시던 통신사의 상품은 해지접수가 취소될수 있으며, 이경우 고객님께서 직접 해지 신청해주셔야 합니다.",note:null},
{id:"ktb001",carrier:"KT_biz",section:"녹취통보",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"안녕하세요 인터넷 접수 받은곳인데요 계약내용에 대한 해피콜 안내 진행하겠습니다.",note:null},
{id:"ktb002",carrier:"KT_biz",section:"명의자 정보",subsection:"일반",ownerTypes:["일반"],order:1,cctvType:null,script:"XXX님, 명의자 본인 되시구요? (네)\n실명확인차 주민번호 앞자리 6자리 확인 부탁드립니다 (고객님이 불러주셔야됨)\n고객님 성별이 남자or여자분 맞으시죠? (네)",note:null},
{id:"ktb003",carrier:"KT_biz",section:"명의자 정보",subsection:"법인/개인사업자",ownerTypes:["법인사업자"],order:1,cctvType:null,script:"(대표자와 녹취) 대표자 000님 본인되시죠? (네)\n(직원과 녹취) 직원이신 000님 본인되시죠? (네)\n\"상호명 00000\", 사업자번호 000-00-00000 명의로 신청하셨죠? (네)",note:null},
{id:"ktb004",carrier:"KT_biz",section:"상품공통",subsection:"공통",ownerTypes:"all",order:1,cctvType:null,script:"신청하신 상품의 총 요금은 월 000원이며 모두 3년 약정입니다.\n사은품은 00상품권 00만원, 현금사은품은 00만원이고 설치비 00원은 다음달에 청구됩니다.\n야간·주말·공휴일 설치시 할증 발생하니 참고 부탁드립니다. (야간 = 평일 9시~18시 그외 시간)\n휴대폰 결합을 원하시면 설치후 다음날 고객센터에 할인 금액, 조건 확인하시고 직접 신청해 주시면 됩니다.\n현금사은품은 19시 전후로 입금 되십니다.",note:"법인은 법인명의 휴대폰만 결합가능"},
{id:"ktb005",carrier:"KT_biz",section:"상품-인터넷",subsection:"인터넷(기업)",ownerTypes:"all",order:1,cctvType:null,script:"가입하신 인터넷은 최소 00M 속도까지 보장되며 기업용 회선으로 유동IP는 PC 14대까지 사용가능하지만 \"고정IP\" 필요시에는 유료 부가서비스 가입하셔야 합니다.\n(200M/500M/1G) 이전설치시 기가급이 설치 불가하면 100M상품으로라도 계속 이용해주셔야 하며 일일사용량 300G 초과시 당일에 한해 100M 속도로 제한됩니다.",note:"유동IP = 어쩌다가 IP주소가 변경됨 / 고정IP = 아이피 변경없는 고유 IP"},
{id:"ktb_tv",carrier:"KT_biz",section:"상품-TV",subsection:"TV",ownerTypes:"all",order:1,cctvType:null,script:"기가지니 상품은 3년 약정이며, 개통후 약정내 다른상품으로 변경하시거나 해지시 할인받으셨던 금액이 위약금으로 청구될수 있습니다.",note:null},
{id:"ktb006",carrier:"KT_biz",section:"상품-인터넷전화",subsection:"인터넷전화(기업)",ownerTypes:"all",order:1,cctvType:null,script:"(유무선00요금제) 인터넷전화 단말기 금액은 0000원이나 유무선00요금제 3년 약정으로 단말기금액은 월 oo원이며, 약정만료 이전에 요금제 변경 및 해지시 할인받으셨던 금액이 위약금으로 청구됩니다.\n(유무선00요금제)는 무료음성통화 00분 포함된 요금제이며, 00분 초과시부터 요금 발생되시고 발신번호표시서비스 및 조건별 착신전환 무료 제공된 요금제입니다.\n★인터넷전화 2대 이상일시★ 개통후 KT기업 고객센터 전화하셔서 필요한 무료 부가서비스 추가설정 요청하시면 됩니다.",note:"570G(기가용) 출고가 60,500원 / 570H(메가용) 출고가 50,600원\nkt 기업고객센터 1588-0114"},
{id:"ktb007",carrier:"KT_biz",section:"상품-번호이동",subsection:"번호이동",ownerTypes:"all",order:1,cctvType:null,script:"지금 사용중인 전화는 번호이동이 끝날때 까지 해지나 정지 하시면 안되니 참고하세요.",note:null},
{id:"ktb_tel",carrier:"KT_biz",section:"상품-집전화",subsection:"집전화",ownerTypes:"all",order:1,cctvType:null,script:"신청하신 일반전화의 경우 3,000요금제 3년약정 조건으로 가입비 6만원이 면제 되시며, 약정만료이전 해지및 요금제변경시 가입비가 위약금으로 청구될수 있습니다.\n(신규) 전화번호는 설치가 완료 되어야 확정됩니다.",note:null},
{id:"ktb_usim",carrier:"KT_biz",section:"상품-유심동판",subsection:"유심동판",ownerTypes:"all",order:99,cctvType:null,script:"가입하신 KT휴대폰 00요금제 약정 0년이시고, 0년이내 해지·번호이동·기기변경시 위약금 발생되시구요~\n개통후 단순변심으로인한 취소는 불가하시고, 휴대폰 요금제는 6개월이후 하향가능하시지만\n분실정지·일시정지·미납정지·해지 또는 비정상사용·유심변경·기기변경·가개통·명의변경은 10개월간 불가하시구요.\n10개월이내에는 결합해지도 하시면 안되시고, 안내드린 내용중 한가지라도 위배사항 발생시 지원금 전액환수되시니 주의 부탁드리구요.\n§※ 판매점용 해피콜/ 유심동판 = 인터넷과 함께 KT휴대폰도 동시에 접수된 경우에만 해당",note:null},
{id:"ktb008",carrier:"KT_biz",section:"위약금·환수",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"본계약은 3년 약정 상품으로 약정내 해지시 위약금이 청구 되시며 한가지 상품이라도 개통 당일이나 중도에 해지하시거나 결합해지, 결합변경, (상부점: 유KT-우리(유선기타)일때만 ★비즈성공팩으로 결합★), 해지, 연체, 정지, 명의이전 등 기타 할인프로그램으로 전환, (TV신청시만: 셋탑종류) 또는 요금제 변경, 본사 프로모션 참여시 위약금이 청구될 수 있으며, 설치후 만 12개월 이내 발생되면 추가로 사은품까지 전액 반환하셔야 하니 유의부탁드립니다. 해당상품은 기업용상품으로 복지등록 및 패밀리결합 할인은 불가합니다.\n\n★특히 TV 상품은 어떠한 사유로도 만 9개월 이내 하향시 사은품 환수되며, 가장 낮은채널로 하향시 사은품은 전액 환수되기 때문에 만 9개월 이후에 하향 부탁드립니다.★",note:null},
{id:"ktb_log",carrier:"KT_biz",section:"클레임 방어",subsection:"물류사은품",ownerTypes:"all",order:91,cctvType:null,script:"(물류사은품) 물류사은품은 수령 이후에는 반송이 불가능하기 때문에 현금으로 반환해 주시면 됩니다.\n초기 불량 확인 전까지 A/S 신청을 위해 제품박스를 버리지 말아주시고, 사은품 불량 사유는 인터넷 해지 사유가 되지 않습니다.",note:"TV상품별 위약금 - 상품권 금액 - 고객 현금부담금액 + 현금사은품 = 물류사은품 위약금"},
{id:"ktb009",carrier:"KT_biz",section:"개인정보 활용동의",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"서비스제공 등을 위하여 신청인의 성명, 주민번호, 이용시간 및 요금납부자의 성명, 생년월일 등 개인정보를 수집하고 신용정보를 조회하여 가입기간 동안 이용하며 해지후 6개월까지 보유하는데 동의하십니까? (네)\n약정기간 만료, 요금감면 행사 등 마케팅 활용에 동의 하시나요? (네)/(아니요) (Yes를 유도해주세요)",note:"은행권 신용정보가 아니구요 단순 연체 조회입니다~\n동의 하지 않으시면 서비스 제공이 어려우니 동의 부탁드려요\n마케팅 활용 동의 거부시 이름뒤에 (거부)로 기재해주세요\n\n[해지후 6개월 보유 참고]\n해지 당월 요금은 다음달에 청구해야 하기 때문에 최소 1개월 이상 보관이 필요합니다. 만약 미납이 생기면 그 다음달에도 청구, 또 미납되면 또 그다음달... 이런 식으로 해지후 요금청구에 필요해서 ★최대★ 6개월 보유입니다!\n(예: 4월 해지 → 5월에 요금청구, 미납 시 6월·7월... 최대 10월까지 보유 가능)"},
{id:"ktb011",carrier:"KT_biz",section:"클레임 방어",subsection:"기존고객·소개비",ownerTypes:"all",order:1,cctvType:null,script:"기존에 사용하시던 상품은 자동해지 되지 않으니 직접 해지하셔야합니다.\n신청하신 상품 신규 개통일 기준으로 설치 전 해지한 KT 회선이 확인될 경우 또는 설치 후 1년 이내 해지, 정지가 확인될 경우 신규로 개통 받으신 사은품 전액 반환될 수 있으며 본사 소명차 추가서류 확인이 필요할수있으니 참고해주세요.\n(소개비) 소개시 1명당 6만원 입금해드리고 있으니 많은 소개 부탁드립니다.(판매점X)\n(설치전) 사유무관하게 00일까지 설치와 결합이 되지 않으면 사은품이 지급되지 않습니다.\n(설치전) 설치 전 상품 변경시 사은품 변동될 수 있으니 변경희망 시 꼭 저희한테 연락주셔야 하구요.\n(주소증빙시) 현금사은품은 개통 후 저희쪽으로 연락주시고 주소증빙이 완료되면 입금됩니다.",note:null},
{id:"ktb012",carrier:"KT_biz",section:"클레임 방어",subsection:"내선공사 안내",ownerTypes:"all",order:2,cctvType:null,script:"(개통후 PASS) (내선공사완료 안내) 기존에 내선공사는 고객님이 직접 해주셔야 하며 KT 기사님은 모뎀만 연결해드립니다. 내선공사 되지 않았을 경우 설치가 보류됩니다!! 참고 부탁드릴게요~",note:null},
{id:"ktb_wonestop",carrier:"KT_biz",section:"클레임 방어",subsection:"원스톱 해지",ownerTypes:"all",order:3,cctvType:null,script:"(원스톱해지 가입고객) 원스톱 해지신청으로 해지가능한 기존통신사의 상품은 인터넷과 TV상품에 한하며, 이외 사용하시던 기존상품들은 고객님께서 별도로 해지해주셔야 합니다.\n최초 신청시 정해진 개통일정에서 임의로 설치일정 변경, 기타사유로 인한 설치지연 등으로 설치일정이 변경될 경우 기존 이용하시던 통신사의 상품은 해지접수가 취소될수 있으며, 이경우 고객님께서 직접 해지 신청해주셔야 합니다.",note:null},
{id:"ktr001",carrier:"KT_renew",section:"녹취통보",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"안녕하세요 인터넷 접수 받은곳인데요 계약내용에 대한 해피콜 안내 진행하겠습니다.",note:null},
{id:"ktr002",carrier:"KT_renew",section:"명의자 정보",subsection:"일반",ownerTypes:["일반"],order:1,cctvType:null,script:"XXX님, 명의자 본인 되시구요? (네)\n실명확인차 주민번호 앞자리 6자리 확인 부탁드립니다 (고객님이 불러주셔야됨)\n고객님 성별이 남자or여자분 맞으시죠? (네)",note:null},
{id:"ktr003",carrier:"KT_renew",section:"명의자 정보",subsection:"법인/개인사업자",ownerTypes:["법인사업자"],order:1,cctvType:null,script:"(대표자와 녹취) 대표자 000님 본인되시죠? (네)\n(직원과 녹취) 직원이신 000님 본인되시죠? (네)\n\"상호명 00000\", 사업자번호 000-00-00000 명의로 신청하셨죠? (네)",note:null},
{id:"ktr004",carrier:"KT_renew",section:"상품공통",subsection:"약정갱신 공통",ownerTypes:"all",order:1,cctvType:null,script:"약정갱신 상품은 모두 3년 약정입니다.\n사은품은 00상품권 00만원, 현금사은품은 00만원이고 설치비 00원은 다음달에 청구됩니다. (기사님 내방해야하는 경우만 안내)\n현금사은품은 19시 전후로 입금 되십니다.",note:null},
{id:"ktr005",carrier:"KT_renew",section:"위약금·환수",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"본계약은 3년 약정 상품으로 약정내 해지시 위약금이 청구 되시며 만 12개월(3사공통) 이내 한가지 상품이라도 개통 당일이나 중도 해지 셋탑 또는 요금제 변경, 결합해지, 복지등록, 해지, 연체, 정지, 명의이전, 패밀리 결합, 교육청 할인, \"KT 따로살아도 가족결합\" 등 기타 할인프로그램 등록, 기업용 상품과 결합 또는 전환, 본사 프로모션 참여시 위약금 발생할 수 있고 사은품까지 전액 반환되니 유의 부탁드리구요\n\n★특히 TV 상품은 어떠한 사유로도 만 9개월 이내 하향시 사은품 환수되며, 가장 낮은채널로 하향시 사은품은 전액 환수되기 때문에 만 9개월 이후에 하향 부탁드립니다.★",note:null},
{id:"ktr_log",carrier:"KT_renew",section:"클레임 방어",subsection:"물류사은품",ownerTypes:"all",order:91,cctvType:null,script:"(물류사은품) 물류사은품은 수령 이후에는 반송이 불가능하기 때문에 현금으로 반환해 주시면 됩니다.\n초기 불량 확인 전까지 A/S 신청을 위해 제품박스를 버리지 말아주시고, 사은품 불량 사유는 인터넷 해지 사유가 되지 않습니다.",note:"TV상품별 위약금 - 상품권 금액 - 고객 현금부담금액 + 현금사은품 = 물류사은품 위약금"},
{id:"ktr007",carrier:"KT_renew",section:"개인정보 활용동의",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"서비스제공 등을 위하여 신청인의 성명, 주민번호, 이용시간 및 요금납부자의 성명, 생년월일 등 개인정보를 수집하고 신용정보를 조회하여 가입기간 동안 이용하며 해지후 6개월까지 보유하는데 동의하십니까? (네)\n약정기간 만료, 요금감면 행사 등 마케팅 활용에 동의 하시나요? (네)/(아니요) (Yes를 유도해주세요)",note:"은행권 신용정보가 아니구요 단순 연체 조회입니다~\n동의 하지 않으시면 서비스 제공이 어려우니 동의 부탁드려요\n마케팅 활용 동의 거부시 이름뒤에 (거부)로 기재해주세요\n\n[해지후 6개월 보유 참고]\n해지 당월 요금은 다음달에 청구해야 하기 때문에 최소 1개월 이상 보관이 필요합니다. 만약 미납이 생기면 그 다음달에도 청구, 또 미납되면 또 그다음달... 이런 식으로 해지후 요금청구에 필요해서 ★최대★ 6개월 보유입니다!\n(예: 4월 해지 → 5월에 요금청구, 미납 시 6월·7월... 최대 10월까지 보유 가능)"},
{id:"ktr006",carrier:"KT_renew",section:"클레임 방어",subsection:"갱신 취소 불가",ownerTypes:"all",order:1,cctvType:null,script:"(공통) 약정갱신을 취소하는 경우 3년이내에는 약정갱신 신청이 불가능하시며 이전의 요금제로는 원복이 불가능합니다.\n기존에 복지할인 및 장기할인을 받고 계신 경우 약정갱신 진행시 해당 할인이 종료될수있으며, 이후에는 복지 및 장기할인 등이 재등록되지 않을 수 있습니다.",note:null},
{id:"ktr_wonestop",carrier:"KT_renew",section:"클레임 방어",subsection:"원스톱 해지",ownerTypes:"all",order:2,cctvType:null,script:"(원스톱해지 가입고객) 원스톱 해지신청으로 해지가능한 기존통신사의 상품은 인터넷과 TV상품에 한하며, 이외 사용하시던 기존상품들은 고객님께서 별도로 해지해주셔야 합니다.\n최초 신청시 정해진 개통일정에서 임의로 설치일정 변경, 기타사유로 인한 설치지연 등으로 설치일정이 변경될 경우 기존 이용하시던 통신사의 상품은 해지접수가 취소될수 있으며, 이경우 고객님께서 직접 해지 신청해주셔야 합니다.",note:null},
{id:"lg001",carrier:"LG",section:"녹취통보",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"안녕하세요 인터넷 접수 받은곳인데요 계약내용에 대한 해피콜 안내 진행하겠습니다.",note:null},
{id:"lg002",carrier:"LG",section:"기본정보",subsection:"일반",ownerTypes:["일반"],order:1,cctvType:null,script:"XXX님, 명의자 본인 되시구요? (네)\n실명확인차 주민번호 앞자리 6자리 확인 부탁드립니다 (고객님이 불러주셔야됨)\n고객님 성별이 남자or여자분 맞으시죠? (네)",note:null},
{id:"lg003",carrier:"LG",section:"기본정보",subsection:"법인/개인사업자",ownerTypes:["법인사업자"],order:1,cctvType:null,script:"(대표자와 녹취) 대표자 000님 본인되시죠? (네)\n(직원과 녹취) 직원이신 000님 본인되시죠? (네)\n\"상호명 00000\", 사업자번호 000-00-00000 명의로 신청하셨죠? (네)",note:null},
{id:"lg004",carrier:"LG",section:"상품공통",subsection:"공통",ownerTypes:"all",order:1,cctvType:null,script:"신청하신 상품의 총 요금은 월 000원이며 모두 3년 약정입니다.\n사은품은 00상품권 00만원, 현금사은품은 00만원이고 설치비 00원은 다음달에 청구됩니다.\n야간·주말·공휴일 설치시 할증 발생하니 참고 부탁드립니다.\n휴대폰 결합을 원하시면 설치후 다음날 고객센터에 할인 금액, 조건 확인하시고 직접 신청해 주시면 됩니다.\n현금사은품은 19시 전후로 입금 되십니다.",note:"다음달로 넘어가면 다음달 정책으로 적용받기 때문에 일단 설치를 받지 마시구요"},
{id:"lg005",carrier:"LG",section:"상품-인터넷",subsection:"인터넷",ownerTypes:"all",order:1,cctvType:null,script:"(500M/1G/200M) 이전설치시 기가급이 설치 불가하면 100M상품으로라도 계속 이용해 주셔야 하며 일일사용량 최소 150G 초과시 당일에 한해 100M 속도로 제한됩니다.\nPC는 2대까지 사용 가능하시구요.",note:null},
{id:"lg006",carrier:"LG",section:"상품-TV",subsection:"TV",ownerTypes:"all",order:1,cctvType:null,script:"UHD4셋탑의 의무약정기간은 3년이나 장비임대기간은 5년이므로 3년약정이후 지속이용하실 경우 남은 2년간 임대료는 계속 청구됩니다.",note:"*UHD4: 약정기간 3년(의무 장비임대 기간) / 임대기간 5년(셋탑박스 임대료 지불기간)"},
{id:"lg007",carrier:"LG",section:"상품-인터넷전화",subsection:"인터넷전화",ownerTypes:"all",order:1,cctvType:null,script:"인터넷전화 단말기 금액은 0000원이고 요금제 3년 약정으로 단말기금액과 월 이용료 oo원 이며, 약정만료 이전에 요금제 변경 해지 시 할인금액이 위약금으로 청구됩니다.",note:"*WPI-9900 / 단말금액 121,000원(월 3,362원) / 월 총이용료 표준:5,562원, 표준+:6,662원\n*표준+ / 영상요금제: 정전시 통화 제한됨"},
{id:"lg008",carrier:"LG",section:"상품-번호이동",subsection:"번호이동",ownerTypes:"all",order:1,cctvType:null,script:"지금 사용중인 전화는 번호이동이 끝날때 까지 해지나 정지 하시면 안되니 참고하세요.",note:null},
{id:"lg_usim",carrier:"LG",section:"상품-유심동판",subsection:"유심동판",ownerTypes:"all",order:99,cctvType:null,script:"가입하신 LG휴대폰 00요금제 약정 0년이시고, 0년이내 해지·번호이동·기기변경시 위약금 발생되시구요~\n개통후 단순변심으로인한 취소는 불가하시고, 휴대폰 요금제는 6개월이후 하향가능하시지만\n분실정지·일시정지·미납정지·해지 또는 비정상사용·유심변경·기기변경·가개통·명의변경은 6개월간 불가하시구요.\n6개월이내에는 결합해지도 하시면 안되시고, 안내드린 내용중 한가지라도 위배사항 발생시 지원금 전액환수되시니 주의 부탁드리구요.\n§※ 판매점용 해피콜/ 유심동판 = 인터넷과 함께 LG휴대폰도 동시에 접수된 경우에만 해당",note:null},
{id:"lg009",carrier:"LG",section:"위약금·환수",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"본계약은 3년 약정 상품으로 약정내 해지시 위약금이 청구 되시며 만 12개월(3사공통) 이내 한가지 상품이라도 개통 당일이나 중도 해지 셋탑 또는 요금제 변경, 결합해지, 지로납부로변경, 복지등록, 해지, 연체, 정지, 명의이전, 패밀리 결합, 교육청 할인, 등 기타 할인프로그램 등록, 기업용 상품과 결합 또는 전환, 본사 프로모션 참여시 위약금 발생할 수 있고 사은품까지 전액 반환되니 유의 부탁드리구요",note:null},
{id:"lg010",carrier:"LG",section:"클레임 방어",subsection:"물류사은품",ownerTypes:"all",order:91,cctvType:null,script:"(물류사은품) 물류사은품은 수령 이후에는 반송이 불가능하기 때문에 현금으로 반환해 주시면 됩니다.\n초기 불량 확인 전까지 A/S 신청을 위해 제품박스를 버리지 말아주시고, 사은품 불량 사유는 인터넷 해지 사유가 되지 않습니다.",note:"TV상품별 위약금 - 상품권 금액 - 고객 현금부담금액 + 현금사은품 = 물류사은품 위약금"},
{id:"lg011",carrier:"LG",section:"개인정보 활용동의",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"서비스제공 등을 위하여 신청인의 성명, 주민번호, 이용시간 및 요금납부자의 성명, 생년월일 등 개인정보를 수집하고 신용정보를 조회하여 가입기간 동안 이용하며 해지후 6개월까지 보유하는데 동의하십니까? (네)\n약정기간 만료, 요금감면 행사 등 마케팅 활용에 동의 하시나요? (네)/(아니요) (Yes를 유도해주세요)",note:"은행권 신용정보가 아니구요 단순 연체 조회입니다~\n동의 하지 않으시면 서비스 제공이 어려우니 동의 부탁드려요\n마케팅 활용 동의 거부시 이름뒤에 (거부)로 기재해주세요\n\n[해지후 6개월 보유 참고]\n해지 당월 요금은 다음달에 청구해야 하기 때문에 최소 1개월 이상 보관이 필요합니다. 만약 미납이 생기면 그 다음달에도 청구, 또 미납되면 또 그다음달... 이런 식으로 해지후 요금청구에 필요해서 ★최대★ 6개월 보유입니다!\n(예: 4월 해지 → 5월에 요금청구, 미납 시 6월·7월... 최대 10월까지 보유 가능)"},
{id:"lg013",carrier:"LG",section:"클레임 방어",subsection:"기존고객·소개비",ownerTypes:"all",order:1,cctvType:null,script:"기존에 사용하시던 상품은 자동해지 되지 않으니 직접 해지하셔야합니다.\n신청하신 인터넷상품 신규개통일 기준으로 설치장소, 사용 명의와 관계없이 설치전 해지한 LG 회선이 확인될 경우 또는, 설치 후 1년안에 해지, 정지가 확인될 경우 신규로 개통 받으신 사은품 전액 반환될 수 있으며 본사 소명차 등본, 임대차 계약서등 추가서류 확인이 필요할수있으니 참고해주세요.\n(소개비) 소개시 1명당 6만원 입금해드리고 있으니 많은 소개 부탁드립니다.(판매점X)\n(설치전) 사유무관하게 00일까지 설치와 결합이 되지 않으면 사은품이 지급되지 않습니다.\n(설치전) 설치 전 상품 변경시 사은품 변동될 수 있으니 변경희망 시 꼭 저희한테 연락주셔야 하구요.\n(주소증빙시) 현금사은품은 개통 후 저희쪽으로 연락주시고 주소증빙이 완료되면 입금됩니다.",note:null},
{id:"lg_wonestop",carrier:"LG",section:"클레임 방어",subsection:"원스톱 해지",ownerTypes:"all",order:2,cctvType:null,script:"(원스톱해지 가입고객) 원스톱 해지신청으로 해지가능한 기존통신사의 상품은 인터넷과 TV상품에 한하며, 이외 사용하시던 기존상품들은 고객님께서 별도로 해지해주셔야 합니다.\n최초 신청시 정해진 개통일정에서 임의로 설치일정 변경, 기타사유로 인한 설치지연 등으로 설치일정이 변경될 경우 기존 이용하시던 통신사의 상품은 해지접수가 취소될수 있으며, 이경우 고객님께서 직접 해지 신청해주셔야 합니다.",note:null},
{id:"lgb001",carrier:"LG_biz",section:"녹취통보",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"안녕하세요 인터넷 접수 받은곳인데요 계약내용에 대한 해피콜 안내 진행하겠습니다.",note:null},
{id:"lgb002",carrier:"LG_biz",section:"기본정보",subsection:"일반",ownerTypes:["일반"],order:1,cctvType:null,script:"XXX님, 명의자 본인 되시구요? (네)\n실명확인차 주민번호 앞자리 6자리 확인 부탁드립니다 (고객님이 불러주셔야됨)\n고객님 성별이 남자or여자분 맞으시죠? (네)",note:null},
{id:"lgb003",carrier:"LG_biz",section:"기본정보",subsection:"법인/개인사업자",ownerTypes:["법인사업자"],order:1,cctvType:null,script:"(대표자와 녹취) 대표자 000님 본인되시죠? (네)\n(직원과 녹취) 직원이신 000님 본인되시죠? (네)\n\"상호명 00000\", 사업자번호 000-00-00000 명의로 신청하셨죠? (네)",note:null},
{id:"lgb004",carrier:"LG_biz",section:"상품공통",subsection:"공통",ownerTypes:"all",order:1,cctvType:null,script:"신청하신 상품의 총 요금은 월 000원이며 모두 3년 약정입니다.\n사은품은 00상품권 00만원, 현금사은품은 00만원이고 설치비 00원은 다음달에 청구됩니다.\n야간·주말·공휴일 설치시 할증 발생하니 참고 부탁드립니다.\n휴대폰 결합을 원하시면 설치후 다음날 고객센터에 할인 금액, 조건 확인하시고 직접 신청해 주시면 됩니다.\n현금사은품은 19시 전후로 입금 되십니다.",note:"다음달로 넘어가면 다음달 정책으로 적용받기 때문에 일단 설치를 받지 마시구요"},
{id:"lgb006",carrier:"LG_biz",section:"상품-인터넷",subsection:"LG소호/오피스넷",ownerTypes:"all",order:1,cctvType:null,script:"(LG소호) 기업용 상품으로 회선당 컴퓨터 2대까지 이용가능하며 추가이용 원할시 월 5,500원에 총 10회선까지 이용 가능합니다.\n(LG오피스넷) 기업용 상품으로 회선당 유동아이피는 무제한으로 이용하실 수 있습니다.\n(200M/500M/1G) 이전설치시 기가급이 설치 불가하면 100M상품으로라도 계속 이용해주셔야 하며 일일사용량 300G 초과시 당일에 한해 100M 속도로 제한됩니다.",note:"25년 2월 1일 접수부터 기본 2대까지, 패키지 추가시 10대"},
{id:"lgb_tv",carrier:"LG_biz",section:"상품-TV",subsection:"TV",ownerTypes:"all",order:1,cctvType:null,script:"UHD4셋탑의 의무약정기간은 3년이나 장비임대기간은 5년이므로 3년약정이후 지속이용하실 경우 남은 2년간 임대료는 계속 청구됩니다.",note:"*UHD4: 약정기간 3년(의무 장비임대 기간) / 임대기간 5년(셋탑박스 임대료 지불기간)"},
{id:"lgb005",carrier:"LG_biz",section:"상품-인터넷전화",subsection:"제로콜/팩스 안내",ownerTypes:"all",order:1,cctvType:null,script:"※정액제요금제(자유통화)는 제로콜 대상 아님※\n자유통화0 요금제 3년 약정으로 단말기금액은 월 oo원 이며, 약정만료 이전에 요금제 변경 및 해지시 할인받으셨던 금액이 위약금으로 청구됩니다.\n★팩스신청시★ 월 요금은 2,200원이며 개통후 만 4개월동안 한달에 팩스 5회이상 발신해주셔야하며, 미발신시 사은품 환수됩니다★",note:null},
{id:"lgb_move",carrier:"LG_biz",section:"상품-번호이동",subsection:"번호이동",ownerTypes:"all",order:1,cctvType:null,script:"지금 사용중인 전화는 번호이동이 끝날때 까지 해지나 정지 하시면 안되니 참고하세요.",note:null},
{id:"lgb007",carrier:"LG_biz",section:"위약금·환수",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"(3년 결합상품이기 때문에) 한가지 상품이라도 중도에 해지하시면 위약금 및 할인반환금이 발생되며, 위약금은 결합할인, 설치비, 장비료 등 사용하시면서 총 할인받으셨던 금액입니다.\n(기가류 가입시) 1년 이내 상품 하향시 상품권 금액이 위약금으로 청구되시고, 결합할인 소멸, 사은품금액 반환 및 새로 설치비 청구되시니 변경없이 이용해주시구요.\n실사용 기준으로 1년이내 해지, 명의변경, 일시정지, 연체, 지로납부로 변경, 복지할인 등록시 위약금과는 별도로 사은품까지 전액 반환하셔야 하니까 최소 1년은 이상없이 사용 부탁드리겠습니다.",note:null},
{id:"lgb_log",carrier:"LG_biz",section:"클레임 방어",subsection:"물류사은품",ownerTypes:"all",order:91,cctvType:null,script:"(물류사은품) 물류사은품은 수령 이후에는 반송이 불가능하기 때문에 현금으로 반환해 주시면 됩니다.\n초기 불량 확인 전까지 A/S 신청을 위해 제품박스를 버리지 말아주시고, 사은품 불량 사유는 인터넷 해지 사유가 되지 않습니다.",note:"TV상품별 위약금 - 상품권 금액 - 고객 현금부담금액 + 현금사은품 = 물류사은품 위약금"},
{id:"lgb008",carrier:"LG_biz",section:"개인정보 활용동의",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"서비스제공 등을 위하여 신청인의 성명, 주민번호, 이용시간 및 요금납부자의 성명, 생년월일 등 개인정보를 수집하고 신용정보를 조회하여 가입기간 동안 이용하며 해지후 6개월까지 보유하는데 동의하십니까? (네)\n약정기간 만료, 요금감면 행사 등 마케팅 활용에 동의 하시나요? (네)/(아니요) (Yes를 유도해주세요)",note:"은행권 신용정보가 아니구요 단순 연체 조회입니다~\n동의 하지 않으시면 서비스 제공이 어려우니 동의 부탁드려요\n마케팅 활용 동의 거부시 이름뒤에 (거부)로 기재해주세요\n\n[해지후 6개월 보유 참고]\n해지 당월 요금은 다음달에 청구해야 하기 때문에 최소 1개월 이상 보관이 필요합니다. 만약 미납이 생기면 그 다음달에도 청구, 또 미납되면 또 그다음달... 이런 식으로 해지후 요금청구에 필요해서 ★최대★ 6개월 보유입니다!\n(예: 4월 해지 → 5월에 요금청구, 미납 시 6월·7월... 최대 10월까지 보유 가능)"},
{id:"lgb_claim",carrier:"LG_biz",section:"클레임 방어",subsection:"기존고객·소개비",ownerTypes:"all",order:1,cctvType:null,script:"기존에 사용하시던 상품은 자동해지 되지 않으니 직접 해지하셔야합니다.\n신청하신 인터넷상품 신규개통일 기준으로 설치장소, 사용 명의와 관계없이 설치전 해지한 LG 회선이 확인될 경우 또는, 설치 후 1년안에 해지, 정지가 확인될 경우 신규로 개통 받으신 사은품 전액 반환될 수 있으며 본사 소명차 등본, 임대차 계약서등 추가서류 확인이 필요할수있으니 참고해주세요.\n(소개비) 소개시 1명당 6만원 입금해드리고 있으니 많은 소개 부탁드립니다.(판매점X)\n(설치전) 사유무관하게 00일까지 설치와 결합이 되지 않으면 사은품이 지급되지 않습니다.\n(설치전) 설치 전 상품 변경시 사은품 변동될 수 있으니 변경희망 시 꼭 저희한테 연락주셔야 하구요.\n(주소증빙시) 현금사은품은 개통 후 저희쪽으로 연락주시고 주소증빙이 완료되면 입금됩니다.",note:null},
{id:"lgb009",carrier:"LG_biz",section:"클레임 방어",subsection:"내선공사 안내",ownerTypes:"all",order:2,cctvType:null,script:"(개통후 PASS) (내선공사완료 안내) 고객님 내선 공사는 완료되셨나요? 기존에 내선공사는 고객님이 직접 해주셔야 하며, 기사님 현장 방문하셔서 외선 및 내선 실사확인차 1~2번 방문예정이시고, 혹시라도 LG 기사님께 내선공사 요청하실경우 현장에서 기사님이 견적 추가로 안내해드릴것이며, 대략적으로 허브에서 PC까지 1회선당 33,000원 청구됩니다.",note:null},
{id:"lgb_wonestop",carrier:"LG_biz",section:"클레임 방어",subsection:"원스톱 해지",ownerTypes:"all",order:3,cctvType:null,script:"(원스톱해지 가입고객) 원스톱 해지신청으로 해지가능한 기존통신사의 상품은 인터넷과 TV상품에 한하며, 이외 사용하시던 기존상품들은 고객님께서 별도로 해지해주셔야 합니다.\n최초 신청시 정해진 개통일정에서 임의로 설치일정 변경, 기타사유로 인한 설치지연 등으로 설치일정이 변경될 경우 기존 이용하시던 통신사의 상품은 해지접수가 취소될수 있으며, 이경우 고객님께서 직접 해지 신청해주셔야 합니다.",note:null},
{id:"sk001",carrier:"SK",section:"녹취통보",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"안녕하세요 인터넷 접수 받은곳인데요 계약내용에 대한 해피콜 안내 진행하겠습니다.",note:null},
{id:"sk002",carrier:"SK",section:"기본정보",subsection:"일반",ownerTypes:["일반"],order:1,cctvType:null,script:"XXX님, 명의자 본인 되시구요? (네)\n실명확인차 주민번호 앞자리 6자리 확인 부탁드립니다 (고객님이 불러주셔야됨)\n고객님 성별이 남자or여자분 맞으시죠? (네)",note:null},
{id:"sk003",carrier:"SK",section:"기본정보",subsection:"법인/개인사업자",ownerTypes:["법인사업자"],order:1,cctvType:null,script:"(대표자와 녹취) 대표자 000님 본인되시죠? (네)\n(직원과 녹취) 직원이신 000님 본인되시죠? (네)\n\"상호명 00000\", 사업자번호 000-00-00000 명의로 신청하셨죠? (네)",note:null},
{id:"sk004",carrier:"SK",section:"상품공통",subsection:"공통",ownerTypes:"all",order:1,cctvType:null,script:"신청하신 상품의 총 요금은 월 000원이며 모두 3년 약정입니다.\n사은품은 00상품권 00만원, 현금사은품은 00만원이고 설치비 00원은 다음달에 청구됩니다.\n야간·주말·공휴일 설치시 할증 발생하니 참고 부탁드립니다.\n휴대폰 결합을 원하시면 설치후 다음날 고객센터에 할인 금액, 조건 확인하시고 직접 신청해 주시면 됩니다.\n현금사은품은 19시 전후로 입금 되십니다.",note:"다음달로 넘어가면 다음달 정책으로 적용받기 때문에 일단 설치를 받지 마시구요"},
{id:"sk005",carrier:"SK",section:"상품-인터넷",subsection:"인터넷",ownerTypes:"all",order:1,cctvType:null,script:"(500M/1G) 이전설치시 기가급이 설치 불가하면 100M상품으로라도 계속 이용해 주셔야 하며 일일사용량 최소 150G 초과시 당일에 한해 100M 속도로 제한됩니다.\nPC는 2대까지 사용 가능합니다.",note:null},
{id:"sk006",carrier:"SK",section:"상품-TV",subsection:"TV(BTV)/애플셋탑",ownerTypes:"all",order:1,cctvType:null,script:"(TV 단품신청고객) 사용중이신 SK인터넷을 해지하시면 TV서비스를 이용할 수 없으며 TV중도 해지시 위약금이 발생할 수 있습니다.\n(애플셋탑) 애플셋탑은 임대가 아닌 판매장비입니다. 기기값 237,600원이며 반품으로 인한 교환 반품 시 기기값이 위약금으로 청구됩니다.\n고장시 SK기사가 아닌 애플센터 방문하셔야 A/S 가능하세요.",note:null},
{id:"sk007",carrier:"SK",section:"상품-인터넷전화",subsection:"인터넷전화",ownerTypes:"all",order:1,cctvType:null,script:"인터넷전화 단말기 금액은 0000원이고 요금제 3년 약정으로 단말기금액과 월 이용료 oo원 이며, 약정만료 이전에 요금제 변경 해지 시 할인금액이 위약금으로 청구됩니다.",note:"*MWP-2500H / 단말금액 88,000원(월 2,400원) / 월 총이용료 3,500원"},
{id:"sk008",carrier:"SK",section:"상품-번호이동",subsection:"번호이동",ownerTypes:"all",order:1,cctvType:null,script:"지금 사용중인 전화는 번호이동이 끝날때 까지 해지나 정지 하시면 안되니 참고하세요.",note:null},
{id:"sk_tel",carrier:"SK",section:"상품-집전화",subsection:"집전화",ownerTypes:"all",order:1,cctvType:null,script:"일반전화 요금제 3년약정으로 월요금은 0000원입니다. 약정만료 이전에 요금제 변경 해지 시 할인금액이 위약금으로 청구됩니다.",note:"*월요금 1,100원"},
{id:"sk_usim",carrier:"SK",section:"상품-유심동판",subsection:"유심동판",ownerTypes:"all",order:99,cctvType:null,script:"가입하신 SK휴대폰 00요금제 약정 0년이시고, 0년이내 해지·번호이동·기기변경시 위약금 발생되시구요~\n개통후 단순변심으로인한 취소는 불가하시고, 휴대폰 요금제는 6개월이후 하향가능하시지만\n분실정지·일시정지·미납정지·해지 또는 비정상사용·유심변경·기기변경·가개통·명의변경은 6개월간 불가하시구요.\n6개월이내에는 결합해지도 하시면 안되시고, 안내드린 내용중 한가지라도 위배사항 발생시 지원금 전액환수되시니 주의 부탁드리구요.\n§※ 판매점용 해피콜/ 유심동판 = 인터넷과 함께 SK휴대폰도 동시에 접수된 경우에만 해당",note:null},
{id:"sk010",carrier:"SK",section:"위약금·환수",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"본계약은 3년 약정 상품으로 약정내 해지시 위약금이 청구 되시며 만 12개월(3사공통) 이내 한가지 상품이라도 개통 당일이나 중도 해지 셋탑 또는 요금제 변경, 결합해지, 지로납부로변경, 복지등록, 해지, 연체, 정지, 명의이전, 패밀리 결합, 교육청 할인, 등 기타 할인프로그램 등록, 기업용 상품과 결합 또는 전환, 본사 프로모션 참여시 위약금 발생할 수 있고 사은품까지 전액 반환되니 유의 부탁드리구요\n유무선 결합은 개통 후 30일 이내로 가능하니 참고 부탁드리겠습니다.",note:null},
{id:"sk_log",carrier:"SK",section:"클레임 방어",subsection:"물류사은품",ownerTypes:"all",order:91,cctvType:null,script:"(물류사은품) 물류사은품은 수령 이후에는 반송이 불가능하기 때문에 현금으로 반환해 주시면 됩니다.\n초기 불량 확인 전까지 A/S 신청을 위해 제품박스를 버리지 말아주시고, 사은품 불량 사유는 인터넷 해지 사유가 되지 않습니다.",note:"TV상품별 위약금 - 상품권 금액 - 고객 현금부담금액 + 현금사은품 = 물류사은품 위약금"},
{id:"sk009",carrier:"SK",section:"개인정보 활용동의",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"서비스제공 등을 위하여 신청인의 성명, 주민번호, 이용시간 및 요금납부자의 성명, 생년월일 등 개인정보를 수집하고 신용정보를 조회하여 가입기간 동안 이용하며 해지후 6개월까지 보유하는데 동의하십니까? (네)\n약정기간 만료, 요금감면 행사 등 마케팅 활용에 동의 하시나요? (네)/(아니요) (Yes를 유도해주세요)",note:"은행권 신용정보가 아니구요 단순 연체 조회입니다~\n동의 하지 않으시면 서비스 제공이 어려우니 동의 부탁드려요\n마케팅 활용 동의 거부시 이름뒤에 (거부)로 기재해주세요\n\n[해지후 6개월 보유 참고]\n해지 당월 요금은 다음달에 청구해야 하기 때문에 최소 1개월 이상 보관이 필요합니다. 만약 미납이 생기면 그 다음달에도 청구, 또 미납되면 또 그다음달... 이런 식으로 해지후 요금청구에 필요해서 ★최대★ 6개월 보유입니다!\n(예: 4월 해지 → 5월에 요금청구, 미납 시 6월·7월... 최대 10월까지 보유 가능)"},
{id:"sk012",carrier:"SK",section:"클레임 방어",subsection:"기존고객·소개비",ownerTypes:"all",order:1,cctvType:null,script:"기존에 사용하시던 상품은 자동해지 되지 않으니 직접 해지하셔야합니다.\n신청하신 인터넷상품 신규개통일 기준으로 설치장소, 사용명의와 관계없이 설치전 해지한 SK 회선이 확인될 경우 또는, 설치 후 1년안에 해지, 정지가 확인될 경우 신규로 개통 받으신 사은품 전액 반환될 수 있으며 본사 소명차 추가서류 확인이 필요할수있으니 참고해주세요.\n(소개비) 소개시 1명당 6만원 입금해드리고 있으니 많은 소개 부탁드립니다.(판매점X)\n(설치전) 사유무관하게 00일까지 설치와 결합이 되지 않으면 사은품이 지급되지 않습니다.\n(설치전) 설치 전 상품 변경시 사은품 변동될 수 있으니 변경희망 시 꼭 저희한테 연락주셔야 하구요.\n(주소증빙시) 현금사은품은 개통 후 저희쪽으로 연락주시고 주소증빙이 완료되면 입금됩니다.",note:null},
{id:"sk_wonestop",carrier:"SK",section:"클레임 방어",subsection:"원스톱 해지",ownerTypes:"all",order:2,cctvType:null,script:"(원스톱해지 가입고객) 원스톱 해지신청으로 해지가능한 기존통신사의 상품은 인터넷과 TV상품에 한하며, 이외 사용하시던 기존상품들은 고객님께서 별도로 해지해주셔야 합니다.\n최초 신청시 정해진 개통일정에서 임의로 설치일정 변경, 기타사유로 인한 설치지연 등으로 설치일정이 변경될 경우 기존 이용하시던 통신사의 상품은 해지접수가 취소될수 있으며, 이경우 고객님께서 직접 해지 신청해주셔야 합니다.",note:null},
{id:"skb_001",carrier:"SK_biz",section:"녹취통보",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"안녕하세요 인터넷 접수 받은곳인데요 계약내용에 대한 해피콜 안내 진행하겠습니다.",note:null},
{id:"skb_002",carrier:"SK_biz",section:"기본정보",subsection:"일반",ownerTypes:["일반"],order:1,cctvType:null,script:"XXX님, 명의자 본인 되시구요? (네)\n실명확인차 주민번호 앞자리 6자리 확인 부탁드립니다 (고객님이 불러주셔야됨)\n고객님 성별이 남자or여자분 맞으시죠? (네)",note:null},
{id:"skb_003",carrier:"SK_biz",section:"기본정보",subsection:"법인/개인사업자",ownerTypes:["법인사업자"],order:1,cctvType:null,script:"(대표자와 녹취) 대표자 000님 본인되시죠? (네)\n(직원과 녹취) 직원이신 000님 본인되시죠? (네)\n\"상호명 00000\", 사업자번호 000-00-00000 명의로 신청하셨죠? (네)",note:null},
{id:"skb_004",carrier:"SK_biz",section:"상품공통",subsection:"공통",ownerTypes:"all",order:1,cctvType:null,script:"신청하신 상품의 총 요금은 월 000원이며 모두 3년 약정입니다.\n사은품은 00상품권 00만원, 현금사은품은 00만원이고 설치비 00원은 다음달에 청구됩니다.\n야간·주말·공휴일 설치시 할증 발생하니 참고 부탁드립니다.\n휴대폰 결합을 원하시면 설치후 다음날 고객센터에 할인 금액, 조건 확인하시고 직접 신청해 주시면 됩니다.\n현금사은품은 19시 전후로 입금 되십니다.",note:"다음달로 넘어가면 다음달 정책으로 적용받기 때문에 일단 설치를 받지 마시구요"},
{id:"skb_005",carrier:"SK_biz",section:"상품-인터넷",subsection:"인터넷",ownerTypes:"all",order:1,cctvType:null,script:"(500M/1G) 이전설치시 기가급이 설치 불가하면 100M상품으로라도 계속 이용해 주셔야 하며 일일사용량 최소 150G 초과시 당일에 한해 100M 속도로 제한됩니다.\nPC는 2대까지 사용 가능합니다.",note:null},
{id:"skb_006",carrier:"SK_biz",section:"상품-TV",subsection:"TV(BTV)/애플셋탑",ownerTypes:"all",order:1,cctvType:null,script:"(TV 단품신청고객) 사용중이신 SK인터넷을 해지하시면 TV서비스를 이용할 수 없으며 TV중도 해지시 위약금이 발생할 수 있습니다.\n(애플셋탑) 애플셋탑은 임대가 아닌 판매장비입니다. 기기값 237,600원이며 반품으로 인한 교환 반품 시 기기값이 위약금으로 청구됩니다.\n고장시 SK기사가 아닌 애플센터 방문하셔야 A/S 가능하세요.",note:null},
{id:"skb_007",carrier:"SK_biz",section:"상품-인터넷전화",subsection:"인터넷전화",ownerTypes:"all",order:1,cctvType:null,script:"인터넷전화 단말기 금액은 0000원이고 요금제 3년 약정으로 단말기금액과 월 이용료 oo원 이며, 약정만료 이전에 요금제 변경 해지 시 할인금액이 위약금으로 청구됩니다.",note:"*MWP-2500H / 단말금액 88,000원(월 2,400원) / 월 총이용료 3,500원"},
{id:"skb_008",carrier:"SK_biz",section:"상품-번호이동",subsection:"번호이동",ownerTypes:"all",order:1,cctvType:null,script:"지금 사용중인 전화는 번호이동이 끝날때 까지 해지나 정지 하시면 안되니 참고하세요.",note:null},
{id:"skb_tel",carrier:"SK_biz",section:"상품-집전화",subsection:"집전화",ownerTypes:"all",order:1,cctvType:null,script:"일반전화 요금제 3년약정으로 월요금은 0000원입니다. 약정만료 이전에 요금제 변경 해지 시 할인금액이 위약금으로 청구됩니다.",note:"*월요금 1,100원"},
{id:"skb_usim",carrier:"SK_biz",section:"상품-유심동판",subsection:"유심동판",ownerTypes:"all",order:99,cctvType:null,script:"가입하신 SK휴대폰 00요금제 약정 0년이시고, 0년이내 해지·번호이동·기기변경시 위약금 발생되시구요~\n개통후 단순변심으로인한 취소는 불가하시고, 휴대폰 요금제는 6개월이후 하향가능하시지만\n분실정지·일시정지·미납정지·해지 또는 비정상사용·유심변경·기기변경·가개통·명의변경은 6개월간 불가하시구요.\n6개월이내에는 결합해지도 하시면 안되시고, 안내드린 내용중 한가지라도 위배사항 발생시 지원금 전액환수되시니 주의 부탁드리구요.\n§※ 판매점용 해피콜/ 유심동판 = 인터넷과 함께 SK휴대폰도 동시에 접수된 경우에만 해당",note:null},
{id:"skb_010",carrier:"SK_biz",section:"위약금·환수",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"본계약은 3년 약정 상품으로 약정내 해지시 위약금이 청구 되시며 만 12개월(3사공통) 이내 한가지 상품이라도 개통 당일이나 중도 해지 셋탑 또는 요금제 변경, 결합해지, 지로납부로변경, 복지등록, 해지, 연체, 정지, 명의이전, 패밀리 결합, 교육청 할인, 등 기타 할인프로그램 등록, 기업용 상품과 결합 또는 전환, 본사 프로모션 참여시 위약금 발생할 수 있고 사은품까지 전액 반환되니 유의 부탁드리구요\n유무선 결합은 개통 후 30일 이내로 가능하니 참고 부탁드리겠습니다.",note:null},
{id:"skb_log",carrier:"SK_biz",section:"클레임 방어",subsection:"물류사은품",ownerTypes:"all",order:91,cctvType:null,script:"(물류사은품) 물류사은품은 수령 이후에는 반송이 불가능하기 때문에 현금으로 반환해 주시면 됩니다.\n초기 불량 확인 전까지 A/S 신청을 위해 제품박스를 버리지 말아주시고, 사은품 불량 사유는 인터넷 해지 사유가 되지 않습니다.",note:"TV상품별 위약금 - 상품권 금액 - 고객 현금부담금액 + 현금사은품 = 물류사은품 위약금"},
{id:"skb_009",carrier:"SK_biz",section:"개인정보 활용동의",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"서비스제공 등을 위하여 신청인의 성명, 주민번호, 이용시간 및 요금납부자의 성명, 생년월일 등 개인정보를 수집하고 신용정보를 조회하여 가입기간 동안 이용하며 해지후 6개월까지 보유하는데 동의하십니까? (네)\n약정기간 만료, 요금감면 행사 등 마케팅 활용에 동의 하시나요? (네)/(아니요) (Yes를 유도해주세요)",note:"은행권 신용정보가 아니구요 단순 연체 조회입니다~\n동의 하지 않으시면 서비스 제공이 어려우니 동의 부탁드려요\n마케팅 활용 동의 거부시 이름뒤에 (거부)로 기재해주세요\n\n[해지후 6개월 보유 참고]\n해지 당월 요금은 다음달에 청구해야 하기 때문에 최소 1개월 이상 보관이 필요합니다. 만약 미납이 생기면 그 다음달에도 청구, 또 미납되면 또 그다음달... 이런 식으로 해지후 요금청구에 필요해서 ★최대★ 6개월 보유입니다!\n(예: 4월 해지 → 5월에 요금청구, 미납 시 6월·7월... 최대 10월까지 보유 가능)"},
{id:"skb_012",carrier:"SK_biz",section:"클레임 방어",subsection:"기존고객·소개비",ownerTypes:"all",order:1,cctvType:null,script:"기존에 사용하시던 상품은 자동해지 되지 않으니 직접 해지하셔야합니다.\n신청하신 인터넷상품 신규개통일 기준으로 설치장소, 사용명의와 관계없이 설치전 해지한 SK 회선이 확인될 경우 또는, 설치 후 1년안에 해지, 정지가 확인될 경우 신규로 개통 받으신 사은품 전액 반환될 수 있으며 본사 소명차 추가서류 확인이 필요할수있으니 참고해주세요.\n(소개비) 소개시 1명당 6만원 입금해드리고 있으니 많은 소개 부탁드립니다.(판매점X)\n(설치전) 사유무관하게 00일까지 설치와 결합이 되지 않으면 사은품이 지급되지 않습니다.\n(설치전) 설치 전 상품 변경시 사은품 변동될 수 있으니 변경희망 시 꼭 저희한테 연락주셔야 하구요.\n(주소증빙시) 현금사은품은 개통 후 저희쪽으로 연락주시고 주소증빙이 완료되면 입금됩니다.",note:null},
{id:"skb_wonestop",carrier:"SK_biz",section:"클레임 방어",subsection:"원스톱 해지",ownerTypes:"all",order:2,cctvType:null,script:"(원스톱해지 가입고객) 원스톱 해지신청으로 해지가능한 기존통신사의 상품은 인터넷과 TV상품에 한하며, 이외 사용하시던 기존상품들은 고객님께서 별도로 해지해주셔야 합니다.\n최초 신청시 정해진 개통일정에서 임의로 설치일정 변경, 기타사유로 인한 설치지연 등으로 설치일정이 변경될 경우 기존 이용하시던 통신사의 상품은 해지접수가 취소될수 있으며, 이경우 고객님께서 직접 해지 신청해주셔야 합니다.",note:null},
{id:"hv001",carrier:"HV",section:"녹취통보",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"안녕하세요 인터넷 접수 받은곳인데요 계약내용에 대한 해피콜 안내 진행하겠습니다.",note:null},
{id:"hv002",carrier:"HV",section:"기본정보",subsection:"일반",ownerTypes:["일반"],order:1,cctvType:null,script:"XXX님, 명의자 본인 되시구요? (네)\n실명확인차 주민번호 앞자리 6자리 확인 부탁드립니다 (고객님이 불러주셔야됨)\n고객님 성별이 남자or여자분 맞으시죠? (네)",note:null},
{id:"hv003",carrier:"HV",section:"상품공통",subsection:"공통",ownerTypes:"all",order:1,cctvType:null,script:"신청하신 상품의 총 요금은 월 000원이며 모두 3년 약정입니다.\n사은품은 00상품권 00만원, 현금사은품은 00만원이고 설치비 00원은 다음달에 청구됩니다.\n★기존 사용하시는 휴대폰이 SK인경우 개통후 한달이내에만 결합이 가능하니 한달이내 꼭 고객센터로 휴대폰 결합신청 부탁드립니다. (KT, LG폰은 상관 없음)\n현금사은품은 19시 전후로 입금 되십니다.",note:"본사 1855-1000 결합신청후, 1644-2799 서류제출, 상담원전화받기 1811-1011"},
{id:"hv_inet",carrier:"HV",section:"상품-인터넷",subsection:"인터넷",ownerTypes:"all",order:1,cctvType:null,script:"(200M/500M/1G) 이전설치시 기가급이 설치 불가하면 100M상품으로라도 계속 이용해 주셔야 하며 일일사용량 최소 150G 초과시 당일에 한해 100M 속도로 제한됩니다.\nPC는 2대까지 사용 가능하시구요.",note:null},
{id:"hv004",carrier:"HV",section:"상품-TV",subsection:"TV",ownerTypes:"all",order:1,cctvType:null,script:"(TV 단품신청고객) 사용중이신 헬로비전 인터넷을 해지하시면 TV서비스를 이용할 수 없으며 TV중도 해지시 위약금이 발생할 수 있습니다.",note:null},
{id:"hv005",carrier:"HV",section:"상품-인터넷전화",subsection:"인터넷전화(CPG)",ownerTypes:"all",order:1,cctvType:null,script:"월 기본료 2,200원 + @ / 설치비 대당 11,000원 청구\nMTA(CPG) 장비임대료 0원 / WiFi 단말기 신청시 79,200원/36개월할부 = 월 2,200원 추가",note:"헬로비전은 제로콜 차감 없음"},
{id:"hv006",carrier:"HV",section:"상품-번호이동",subsection:"번호이동",ownerTypes:"all",order:1,cctvType:null,script:"지금 사용중인 전화는 번호이동이 끝날때 까지 해지나 정지 하시면 안되니 참고하세요.",note:null},
{id:"hv007",carrier:"HV",section:"위약금·환수",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"본계약은 3년 약정 상품으로 약정내 해지시 위약금이 청구 되시며 만 12개월(3사공통) 이내 한가지 상품이라도 개통 당일이나 중도 해지 셋탑 또는 요금제 변경, 결합해지, 지로납부로변경, 복지등록, 해지, 연체, 정지, 명의이전, 패밀리 결합, 교육청 할인, 등 기타 할인프로그램 등록, 기업용 상품과 결합 또는 전환, 본사 프로모션 참여시 위약금 발생할 수 있고 사은품까지 전액 반환되니 유의 부탁드리구요",note:null},
{id:"hv_log",carrier:"HV",section:"클레임 방어",subsection:"물류사은품",ownerTypes:"all",order:91,cctvType:null,script:"(물류사은품) 물류사은품은 수령 이후에는 반송이 불가능하기 때문에 현금으로 반환해 주시면 됩니다.\n초기 불량 확인 전까지 A/S 신청을 위해 제품박스를 버리지 말아주시고, 사은품 불량 사유는 인터넷 해지 사유가 되지 않습니다.",note:"TV상품별 위약금 - 상품권 금액 - 고객 현금부담금액 + 현금사은품 = 물류사은품 위약금"},
{id:"hv008",carrier:"HV",section:"개인정보 활용동의",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"서비스제공 등을 위하여 신청인의 성명, 주민번호, 이용시간 및 요금납부자의 성명, 생년월일 등 개인정보를 수집하고 신용정보를 조회하여 가입기간 동안 이용하며 해지후 6개월까지 보유하는데 동의하십니까? (네)\n약정기간 만료, 요금감면 행사 등 마케팅 활용에 동의 하시나요? (네)/(아니요) (Yes를 유도해주세요)",note:"은행권 신용정보가 아니구요 단순 연체 조회입니다~\n동의 하지 않으시면 서비스 제공이 어려우니 동의 부탁드려요\n마케팅 활용 동의 거부시 이름뒤에 (거부)로 기재해주세요\n\n[해지후 6개월 보유 참고]\n해지 당월 요금은 다음달에 청구해야 하기 때문에 최소 1개월 이상 보관이 필요합니다. 만약 미납이 생기면 그 다음달에도 청구, 또 미납되면 또 그다음달... 이런 식으로 해지후 요금청구에 필요해서 ★최대★ 6개월 보유입니다!\n(예: 4월 해지 → 5월에 요금청구, 미납 시 6월·7월... 최대 10월까지 보유 가능)"},
{id:"hv009",carrier:"HV",section:"클레임 방어",subsection:"기존고객·소개비",ownerTypes:"all",order:1,cctvType:null,script:"기존에 사용하시던 상품은 자동해지 되지 않으니 직접 해지하셔야합니다.\n신청하신 인터넷상품 신규개통일 기준으로 설치장소, 사용명의와 관계없이 설치전 해지한 헬로비전 회선이 확인될 경우 또는, 설치 후 1년안에 해지, 정지가 확인될 경우 신규로 개통 받으신 사은품 전액 반환될 수 있으며 본사 소명차 추가서류 확인이 필요할수있으니 참고해주세요.\n(소개비) 소개시 1명당 6만원 입금해드리고 있으니 많은 소개 부탁드립니다.(판매점X)\n(설치전) 사유무관하게 00일까지 설치와 결합이 되지 않으면 사은품이 지급되지 않습니다.\n(설치전) 설치 전 상품 변경시 사은품 변동될 수 있으니 변경희망 시 꼭 저희한테 연락주셔야 하구요.\n(주소증빙시) 현금사은품은 개통 후 저희쪽으로 연락주시고 주소증빙이 완료되면 입금됩니다.",note:null},
{id:"hv009b",carrier:"HV",section:"클레임 방어",subsection:"기사 방문시 자동이체 서명",ownerTypes:"all",order:2,cctvType:null,script:"기사님 방문시 PAD에 자동이체 신청하신 부분 확인차 서명 요구할 수 있습니다. 자동이체 신청하셨다는 서명 거부하실 경우 사은품 지급에 문제 생기니 기사님께 꼭 부탁드리며, 저희가 지급해드리는 사은품은 자동이체유지 조건이니 꼭 자동이체 유지 부탁드립니다.",note:"카드이체로 변경하는건 상관없음 / 지로 납부 변경 절대 금지 → 수수료 전액환수"},
{id:"hv_wonestop",carrier:"HV",section:"클레임 방어",subsection:"원스톱 해지",ownerTypes:"all",order:3,cctvType:null,script:"(원스톱해지 가입고객) 원스톱 해지신청으로 해지가능한 기존통신사의 상품은 인터넷과 TV상품에 한하며, 이외 사용하시던 기존상품들은 고객님께서 별도로 해지해주셔야 합니다.\n최초 신청시 정해진 개통일정에서 임의로 설치일정 변경, 기타사유로 인한 설치지연 등으로 설치일정이 변경될 경우 기존 이용하시던 통신사의 상품은 해지접수가 취소될수 있으며, 이경우 고객님께서 직접 해지 신청해주셔야 합니다.",note:null},
{id:"tb001",carrier:"TB",section:"녹취통보",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"안녕하세요 인터넷 접수 받은곳인데요 계약내용에 대한 해피콜 안내 진행하겠습니다.",note:null},
{id:"tb002",carrier:"TB",section:"기본정보",subsection:"일반",ownerTypes:["일반"],order:1,cctvType:null,script:"XXX님, 명의자 본인 되시구요? (네)\n실명확인차 주민번호 앞자리 6자리 확인 부탁드립니다 (고객님이 불러주셔야됨)\n고객님 성별이 남자or여자분 맞으시죠? (네)",note:null},
{id:"tb003",carrier:"TB",section:"기본정보",subsection:"법인/개인사업자",ownerTypes:["법인사업자"],order:1,cctvType:null,script:"(대표자와 녹취) 대표자 000님 본인되시죠? (네)\n(직원과 녹취) 직원이신 000님 본인되시죠? (네)\n\"상호명 00000\", 사업자번호 000-00-00000 명의로 신청하셨죠? (네)",note:null},
{id:"tb004",carrier:"TB",section:"상품공통",subsection:"공통",ownerTypes:"all",order:1,cctvType:null,script:"신청하신 상품의 총 요금은 월 000원이며 모두 3년 약정입니다.\n사은품은 00상품권 00만원, 현금사은품은 00만원이고 설치비 00원은 다음달에 청구됩니다.\n야간·주말·공휴일 설치시 할증 발생하니 참고 부탁드립니다.\n휴대폰 결합을 원하시면 설치후 다음날 고객센터에 할인 금액, 조건 확인하시고 직접 신청해 주시면 됩니다.\n현금사은품은 19시 전후로 입금 되십니다.",note:"다음달로 넘어가면 다음달 정책으로 적용받기 때문에 일단 설치를 받지 마시구요\n하이브리드 → 106번 안내"},
{id:"tb005",carrier:"TB",section:"상품-인터넷",subsection:"인터넷",ownerTypes:"all",order:1,cctvType:null,script:"(500M/1G) 이전설치시 기가급이 설치 불가하면 100M상품으로라도 계속 이용해 주셔야 하며 일일사용량 최소 150G 초과시 당일에 한해 100M 속도로 제한됩니다.\nPC는 2대까지 사용 가능합니다.",note:null},
{id:"tb006",carrier:"TB",section:"상품-TV",subsection:"TV",ownerTypes:"all",order:1,cctvType:null,script:"(TV 단품신청고객) 사용중이신 티브로드 인터넷을 해지하시면 TV서비스를 이용할 수 없으며 TV중도 해지시 위약금이 발생할 수 있습니다.\nTV채널은 본사 사정에 따라 변동될 수 있으니 꼭 필요한 채널이 있으시다면 개통전에 본사로 확인해 주셔야 합니다.",note:null},
{id:"tb007",carrier:"TB",section:"상품-인터넷전화",subsection:"일반전화/인터넷전화(CPG)",ownerTypes:"all",order:1,cctvType:null,script:"인터넷전화 단말기 지급 없음, MTA(CPG)방식만 설치가능. 고객이 전화기 직접 준비해야하며 기본료는 월 2,200원 / 설치비는 대당 +11,000원\n일반전화 설치비 +22,000원 - 인터넷/티비 설치 후 106번으로 번호이동 접수해주세요.",note:"티브로드는 제로콜 차감 없음\n하이브리드 신청시 일반전화신청은 가급적 개통후 106번으로 신청 안내"},
{id:"tb009",carrier:"TB",section:"상품-번호이동",subsection:"번호이동",ownerTypes:"all",order:1,cctvType:null,script:"지금 사용중인 전화는 번호이동이 끝날때 까지 해지나 정지 하시면 안되니 참고하세요.",note:null},
{id:"tb010",carrier:"TB",section:"위약금·환수",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"본계약은 3년 약정 상품으로 약정내 해지시 위약금이 청구 되시며 만 12개월(3사공통) 이내 한가지 상품이라도 개통 당일이나 중도 해지 셋탑 또는 요금제 변경, 결합해지, 지로납부로변경, 복지등록, 해지, 연체, 정지, 명의이전, 패밀리 결합, 교육청 할인, 등 기타 할인프로그램 등록, 기업용 상품과 결합 또는 전환, 본사 프로모션 참여시 위약금 발생할 수 있고 사은품까지 전액 반환되니 유의 부탁드리구요\n유무선 결합은 개통 후 30일 이내로 가능하니 참고 부탁드리겠습니다.\n(★선납권 고객일경우) 선납권은 36개월만 적용가능하시며, 36개월 이후 원래요금으로 청구됩니다. 36개월이후에 꼭 연락주셔서 타사로 이동 부탁드립니다~!",note:"★★ 선납권 고객일경우, 선납권은 36개월만 적용가능하시며, 36개월 이후 원래요금으로 청구됩니다. 36개월이후에 꼭 연락주셔서 타사로 이동 부탁드립니다~!"},
{id:"tb_log",carrier:"TB",section:"클레임 방어",subsection:"물류사은품",ownerTypes:"all",order:91,cctvType:null,script:"(물류사은품) 물류사은품은 수령 이후에는 반송이 불가능하기 때문에 현금으로 반환해 주시면 됩니다.\n초기 불량 확인 전까지 A/S 신청을 위해 제품박스를 버리지 말아주시고, 사은품 불량 사유는 인터넷 해지 사유가 되지 않습니다.",note:"TV상품별 위약금 - 상품권 금액 - 고객 현금부담금액 + 현금사은품 = 물류사은품 위약금"},
{id:"tb011",carrier:"TB",section:"개인정보 활용동의",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"서비스제공 등을 위하여 신청인의 성명, 주민번호, 이용시간 및 요금납부자의 성명, 생년월일 등 개인정보를 수집하고 신용정보를 조회하여 가입기간 동안 이용하며 해지후 6개월까지 보유하는데 동의하십니까? (네)\n약정기간 만료, 요금감면 행사 등 마케팅 활용에 동의 하시나요? (네)/(아니요) (Yes를 유도해주세요)",note:"은행권 신용정보가 아니구요 단순 연체 조회입니다~\n동의 하지 않으시면 서비스 제공이 어려우니 동의 부탁드려요\n마케팅 활용 동의 거부시 이름뒤에 (거부)로 기재해주세요\n\n[해지후 6개월 보유 참고]\n해지 당월 요금은 다음달에 청구해야 하기 때문에 최소 1개월 이상 보관이 필요합니다. 만약 미납이 생기면 그 다음달에도 청구, 또 미납되면 또 그다음달... 이런 식으로 해지후 요금청구에 필요해서 ★최대★ 6개월 보유입니다!\n(예: 4월 해지 → 5월에 요금청구, 미납 시 6월·7월... 최대 10월까지 보유 가능)"},
{id:"tb013",carrier:"TB",section:"클레임 방어",subsection:"기존고객·소개비",ownerTypes:"all",order:1,cctvType:null,script:"기존에 사용하시던 상품은 자동해지 되지 않으니 직접 해지하셔야합니다.\n신청하신 인터넷상품 신규개통일 기준으로 설치장소, 사용명의와 관계없이 설치전 해지한 티브로드 회선이 확인될 경우 또는, 설치 후 1년안에 해지, 정지가 확인될 경우 신규로 개통 받으신 사은품 전액 반환될 수 있으며 본사 소명차 추가서류 확인이 필요할수있으니 참고해주세요.\n(소개비) 소개시 1명당 6만원 입금해드리고 있으니 많은 소개 부탁드립니다.(판매점X)\n(설치전) 사유무관하게 00일까지 설치와 결합이 되지 않으면 사은품이 지급되지 않습니다.\n(설치전) 설치 전 상품 변경시 사은품 변동될 수 있으니 변경희망 시 꼭 저희한테 연락주셔야 하구요.\n(주소증빙시) 현금사은품은 개통 후 저희쪽으로 연락주시고 주소증빙이 완료되면 입금됩니다.",note:null},
{id:"tb_wonestop",carrier:"TB",section:"클레임 방어",subsection:"원스톱 해지",ownerTypes:"all",order:2,cctvType:null,script:"(원스톱해지 가입고객) 원스톱 해지신청으로 해지가능한 기존통신사의 상품은 인터넷과 TV상품에 한하며, 이외 사용하시던 기존상품들은 고객님께서 별도로 해지해주셔야 합니다.\n최초 신청시 정해진 개통일정에서 임의로 설치일정 변경, 기타사유로 인한 설치지연 등으로 설치일정이 변경될 경우 기존 이용하시던 통신사의 상품은 해지접수가 취소될수 있으며, 이경우 고객님께서 직접 해지 신청해주셔야 합니다.",note:null},
{id:"sky001",carrier:"SKY",section:"녹취통보",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"안녕하세요 인터넷 접수 받은곳인데요 계약내용에 대한 해피콜 안내 진행하겠습니다.",note:null},
{id:"sky003",carrier:"SKY",section:"명의자 정보",subsection:"일반",ownerTypes:["일반"],order:1,cctvType:null,script:"XXX님, 명의자 본인 되시구요? (네)\n실명확인차 주민번호 앞자리 6자리 확인 부탁드립니다 (고객님이 불러주셔야됨)\n고객님 성별이 남자or여자분 맞으시죠? (네)",note:null},
{id:"sky004",carrier:"SKY",section:"명의자 정보",subsection:"법인/개인사업자",ownerTypes:["법인사업자"],order:1,cctvType:null,script:"(대표자와 녹취) 대표자 000님 본인되시죠? (네)\n(직원과 녹취) 직원이신 000님 본인되시죠? (네)\n\"상호명 00000\", 사업자번호 000-00-00000 명의로 신청하셨죠? (네)",note:null},
{id:"sky005",carrier:"SKY",section:"명의자 정보",subsection:"법정대리인",ownerTypes:["법정대리인"],order:1,cctvType:null,script:"명의자는 000님 주민번호 앞자리가 000000 남자or여자분 이구요\n통화하시는 고객님은 법정대리인인 000님 주민번호 앞자리가 000000 이시고, 남자or여자분 맞으시죠? (네)",note:null},
{id:"sky007",carrier:"SKY",section:"상품공통",subsection:"공통",ownerTypes:"all",order:1,cctvType:null,script:"신청하신 상품의 총 요금은 월 000원이며 모두 3년 약정입니다.\n사은품은 00상품권 00만원, 현금사은품은 00만원이고 설치비 00원은 다음달에 청구됩니다.\n야간·주말·공휴일 설치시 할증 발생하니 참고 부탁드립니다. (야간 = 평일 9시~18시 그외 시간)\n휴대폰 결합을 원하시면 설치후 다음날 고객센터에 할인 금액, 조건 확인하시고 직접 신청해 주시면 됩니다.\n현금사은품은 19시 전후로 입금 되십니다.\n실제 설치 받으시는 상품이 변경되면 사은품 금액도 달라지고 변수가 많기 때문에 변경 전 저희에게 꼭 연락 주셔야 합니다.",note:null},
{id:"sky008",carrier:"SKY",section:"상품-인터넷",subsection:"인터넷",ownerTypes:"all",order:1,cctvType:null,script:"가입하신 인터넷은 최소 00M 속도까지 보장되며 PC는 2대까지 사용 가능합니다.\n(200M/500M/1G) 이전설치시 기가급이 설치 불가하면 100M상품으로라도 계속 이용해 주셔야 하며 일일사용량 최소 150G 초과시 당일에 한해 100M 속도로 제한됩니다.",note:"요금도 메가급으로 변경됩니다."},
{id:"sky009",carrier:"SKY",section:"상품-TV",subsection:"TV",ownerTypes:"all",order:1,cctvType:null,script:"(스카이/TV 단품) 인터넷을 해지하시면 TV서비스를 이용할 수 없으며 TV중도 해지시 위약금이 발생할 수 있습니다.\n(필수) 집중호우, 폭설 등의 기상악화 또는 인터넷 품질상태에 따라 일시적인 서비스장애가 발생될 수 있습니다.",note:"상품변경: 높은 요금제 상품으로 변경은 관계없음"},
{id:"sky_usim",carrier:"SKY",section:"상품-유심동판",subsection:"유심동판",ownerTypes:"all",order:99,cctvType:null,script:"가입하신 SKY휴대폰 00요금제 약정 0년이시고, 0년이내 해지·번호이동·기기변경시 위약금 발생되시구요~\n개통후 단순변심으로인한 취소는 불가하시고, 휴대폰 요금제는 6개월이후 하향가능하시지만\n분실정지·일시정지·미납정지·해지 또는 비정상사용·유심변경·기기변경·가개통·명의변경은 10개월간 불가하시구요.\n10개월이내에는 결합해지도 하시면 안되시고, 안내드린 내용중 한가지라도 위배사항 발생시 지원금 전액환수되시니 주의 부탁드리구요.\n§※ 판매점용 해피콜/ 유심동판 = 인터넷과 함께 SKY휴대폰도 동시에 접수된 경우에만 해당",note:null},
{id:"sky010",carrier:"SKY",section:"위약금·환수",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"본계약은 3년 약정 상품으로 약정내 해지시 위약금이 청구 되시며 만 12개월(3사공통) 이내 한가지 상품이라도 개통 당일이나 중도 해지 셋탑 또는 요금제 변경, 결합해지, 복지등록, 해지, 연체, 정지, 명의이전, 패밀리 결합, 교육청 할인, \"KT 따로살아도 가족결합\" 등 기타 할인프로그램 등록, 기업용 상품과 결합 또는 전환, 본사 프로모션 참여시 위약금 발생할 수 있고 사은품까지 전액 반환되니 유의 부탁드리구요\n\n★특히 TV 상품은 어떠한 사유로도 만 9개월 이내 하향시 사은품 환수되며, 가장 낮은채널로 하향시 사은품은 전액 환수되기 때문에 만 9개월 이후에 하향 부탁드립니다.★",note:null},
{id:"sky011",carrier:"SKY",section:"클레임 방어",subsection:"물류사은품",ownerTypes:"all",order:91,cctvType:null,script:"(물류사은품) 물류사은품은 수령 이후에는 반송이 불가능하기 때문에 현금으로 반환해 주시면 됩니다.\n초기 불량 확인 전까지 A/S 신청을 위해 제품박스를 버리지 말아주시고, 사은품 불량 사유는 인터넷 해지 사유가 되지 않습니다.",note:"TV상품별 위약금 - 상품권 금액 - 고객 현금부담금액 + 현금사은품 = 물류사은품 위약금"},
{id:"sky012",carrier:"SKY",section:"개인정보 활용동의",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"서비스제공 등을 위하여 신청인의 성명, 주민번호, 이용시간 및 요금납부자의 성명, 생년월일 등 개인정보를 수집하고 신용정보를 조회하여 가입기간 동안 이용하며 해지후 6개월까지 보유하는데 동의하십니까? (네)\n약정기간 만료, 요금감면 행사 등 마케팅 활용에 동의 하시나요? (네)/(아니요) (Yes를 유도해주세요)",note:"은행권 신용정보가 아니구요 단순 연체 조회입니다~\n동의 하지 않으시면 서비스 제공이 어려우니 동의 부탁드려요\n마케팅 활용 동의 거부시 이름뒤에 (거부)로 기재해주세요\n\n[해지후 6개월 보유 참고]\n해지 당월 요금은 다음달에 청구해야 하기 때문에 최소 1개월 이상 보관이 필요합니다. 만약 미납이 생기면 그 다음달에도 청구, 또 미납되면 또 그다음달... 이런 식으로 해지후 요금청구에 필요해서 ★최대★ 6개월 보유입니다!\n(예: 4월 해지 → 5월에 요금청구, 미납 시 6월·7월... 최대 10월까지 보유 가능)"},
{id:"sky014",carrier:"SKY",section:"클레임 방어",subsection:"기존고객·소개비",ownerTypes:"all",order:1,cctvType:null,script:"기존에 사용하시던 상품은 자동해지 되지 않으니 직접 해지하셔야합니다.\n신청하신 상품 신규 개통일 기준으로 설치 장소, 사용명의와 관계없이 설치 전 해지한 스카이라이프 회선이 확인될 경우 또는 설치 후 1년 이내 해지, 정지가 확인될 경우 신규로 개통 받으신 사은품 전액 반환될 수 있으며 본사 소명차 추가서류 확인이 필요할수있으니 참고해주세요.\n(소개비) 소개시 1명당 6만원 입금해드리고 있으니 많은 소개 부탁드립니다.(판매점X)\n(설치전) 사유무관하게 00일까지 설치와 결합이 되지 않으면 사은품이 지급되지 않습니다.\n(설치전) 설치 전 상품 변경시 사은품 변동될 수 있으니 변경희망 시 꼭 저희한테 연락주셔야 하구요.\n(주소증빙시) 현금사은품은 개통 후 저희쪽으로 연락주시고 주소증빙이 완료되면 입금됩니다.",note:null},
{id:"sky_wonestop",carrier:"SKY",section:"클레임 방어",subsection:"원스톱 해지",ownerTypes:"all",order:2,cctvType:null,script:"(원스톱해지 가입고객) 원스톱 해지신청으로 해지가능한 기존통신사의 상품은 인터넷과 TV상품에 한하며, 이외 사용하시던 기존상품들은 고객님께서 별도로 해지해주셔야 합니다.\n최초 신청시 정해진 개통일정에서 임의로 설치일정 변경, 기타사유로 인한 설치지연 등으로 설치일정이 변경될 경우 기존 이용하시던 통신사의 상품은 해지접수가 취소될수 있으며, 이경우 고객님께서 직접 해지 신청해주셔야 합니다.",note:null},
{id:"cctv001",carrier:"CCTV",section:"녹취통보",subsection:null,ownerTypes:"all",order:1,cctvType:"common",script:"안녕하세요 인터넷 접수 받은곳인데요 계약내용에 대한 해피콜 안내 진행하겠습니다.",note:null},
{id:"cctv002",carrier:"CCTV",section:"명의자 정보",subsection:"일반",ownerTypes:["일반"],order:1,cctvType:"common",script:"XXX님, 명의자 본인 되시구요? (네)\n실명확인차 주민번호 앞자리 6자리 확인 부탁드립니다 (고객님이 불러주셔야됨)\n고객님 성별이 남자or여자분 맞으시죠? (네)",note:null},
{id:"cctv003",carrier:"CCTV",section:"명의자 정보",subsection:"법인/개인사업자",ownerTypes:["법인사업자"],order:1,cctvType:"common",script:"(대표자와 녹취) 대표자 000님 본인되시죠? (네)\n(직원과 녹취) 직원이신 000님 본인되시죠? (네)\n\"상호명 00000\", 사업자번호 000-00-00000 명의로 신청하셨죠? (네)",note:null},
{id:"cctv004",carrier:"CCTV",section:"상품 정보",subsection:"CCTV 공통 설치",ownerTypes:"all",order:1,cctvType:"common",script:"신청하신 상품의 총 요금은 월 000원이며 모두 3년 약정입니다.\n(설치전) CCTV 설치비 00원은 4대까지는 기본적으로 무료이나 기사님 방문시 난공사지역이거나, 천장층고가 3M 이상일때, 사무실 한공간이 아니고 다른공간으로 설치할 때도 청구될 수 있는 점 참고 부탁드립니다.\n사용하시다 이전설치하시게 되면 이전비가 청구되시고, 해지시 철거비가 발생될 수 있습니다.\n(실외형 카메라 있을때) 실외형 카메라는 25M까지만 선공사 무료라 혹시 멀리 떨어져있으면 추가 설치비 부과될 수 있습니다.\nCCTV 상품은 3년약정으로 약정내 해지시 할인반환금 및 CCTV 카메라 장비대여금 반환금이 청구됩니다.\n결합해지, 자사인터넷 해지, 연체, 정지, 명의이전 등 기타 할인프로그램으로 전환, 본사 프로모션 참여시 위약금이 청구될 수 있으며, 설치후 1년 이내 발생되면 추가로 사은품까지 전액 반환하셔야 하니 유의부탁드립니다.",note:"면제된 설치비는 약정 내 해지시 위약금으로 청구됩니다."},
{id:"cctv005",carrier:"CCTV",section:"상품 정보",subsection:"텔레캅 전용",ownerTypes:"all",order:1,cctvType:"텔레캅",script:"텔레캅은 방문하셔서 계약서 작성하셨고, 텔레캅상품 3년약정으로 약정내 해지시 할인반환금 및 CCTV 카메라 장비대여금 반환금이 청구됩니다.\n결합해지, 자사인터넷 해지, 연체, 정지, 명의이전 등 기타 할인프로그램으로 전환, 본사 프로모션 참여시 위약금이 청구될 수 있으며, 설치후 1년 이내 발생되면 추가로 사은품까지 전액 반환하셔야 하니 유의부탁드립니다.\n§※KT 인터넷 회선과 결합된 서비스입니다. 이상 감지 시 자동으로 고객님께 알림이 전달되며, 실시간 모니터링이 가능합니다.\n기사님이 보고 현장에서 견적나옴 요금,설치비안내x / 고객센터: 080-700-2700",note:"텔레캅 고객센터: 080-700-2700"},
{id:"cctv006",carrier:"CCTV",section:"상품 정보",subsection:"기가아이즈 전용",ownerTypes:"all",order:1,cctvType:"기가아이즈",script:"신청하신 상품의 총 요금은 월 000원이며 모두 3년 약정입니다.\n(설치전) CCTV 설치비 00원은 4대까지는 기본적으로 무료이나 기사님 방문시 난공사지역이거나, 천장층고가 3M 이상일때, 사무실 한공간이 아니고 다른공간으로 설치할 때도 청구될 수 있는 점 참고 부탁드립니다.\n사용하시다 이전설치하시게 되면 이전비가 청구되시고, 해지시 철거비가 발생될 수 있습니다.\n(실외형 카메라 있을때) 실외형 카메라는 25M까지만 선공사 무료라 혹시 멀리 떨어져있으면 추가 설치비 부과될 수 있습니다.\nCCTV 상품은 3년약정으로 약정내 해지시 할인반환금 및 CCTV 카메라 장비대여금 반환금이 청구됩니다.\n결합해지, 자사인터넷 해지, 연체, 정지, 명의이전 등 기타 할인프로그램으로 전환, 본사 프로모션 참여시 위약금이 청구될 수 있으며, 설치후 1년 이내 발생되면 추가로 사은품까지 전액 반환하셔야 하니 유의부탁드립니다.\n§※ 면제된 설치비는 약정 내 해지시 위약금으로 청구됩니다.\nKT 기가 인터넷 회선과 결합하여 고화질 영상 저장 및 원격 확인이 가능합니다.\n저장 영상은 30일치 보관되며, 이상 이벤트 발생시 앱으로 알림이 전달됩니다.\n기가아이즈 앱 통해 원격 확인 가능",note:"기가아이즈 앱 통해 원격 확인 가능"},
{id:"cctv007",carrier:"CCTV",section:"상품 정보",subsection:"캡스 전용",ownerTypes:"all",order:1,cctvType:"캡스",script:"캡스는 방문하셔서 계약서 작성하셨고, 캡스를 해지하시거나 결합된 SK휴대폰은 최소 4개월 결합유지해주셔야하며 이전에 휴대폰 결합이 해지되면 사은품을 돌려주셔야 합니다.",note:null},
{id:"cctv008",carrier:"CCTV",section:"위약금·환수",subsection:null,ownerTypes:"all",order:1,cctvType:"common",script:"CCTV 상품은 3년약정으로 약정내 해지시 할인반환금 및 CCTV 카메라 장비대여금 반환금 청구됩니다.\n결합해지, 자사인터넷 해지, 연체, 정지, 명의이전 등 기타 할인프로그램으로 전환, 본사 프로모션 참여시 위약금이 청구될 수 있으며, 설치후 1년 이내 발생되면 추가로 사은품까지 전액 반환하셔야 하니 유의부탁드립니다.",note:"장비 판매가 아닌 임대이므로 해지시 통신사로 카메라 반환해야함"},
{id:"cctv_log",carrier:"CCTV",section:"클레임 방어",subsection:"물류사은품",ownerTypes:"all",order:91,cctvType:"common",script:"(물류사은품) 물류사은품은 수령 이후에는 반송이 불가능하기 때문에 현금으로 반환해 주시면 됩니다.\n초기 불량 확인 전까지 A/S 신청을 위해 제품박스를 버리지 말아주시고, 사은품 불량 사유는 인터넷 해지 사유가 되지 않습니다.",note:"TV상품별 위약금 - 상품권 금액 - 고객 현금부담금액 + 현금사은품 = 물류사은품 위약금"},
{id:"cctv009",carrier:"CCTV",section:"개인정보 활용동의",subsection:null,ownerTypes:"all",order:1,cctvType:"common",script:"서비스제공 등을 위하여 신청인의 성명, 주민번호, 이용시간 및 요금납부자의 성명, 생년월일 등 개인정보를 수집하고 신용정보를 조회하여 가입기간 동안 이용하며 해지후 6개월까지 보유하는데 동의하십니까? (네)\n약정기간 만료, 요금감면 행사 등 마케팅 활용에 동의 하시나요? (네)/(아니요) (Yes를 유도해주세요)",note:"은행권 신용정보가 아니구요 단순 연체 조회입니다~\n동의 하지 않으시면 서비스 제공이 어려우니 동의 부탁드려요\n마케팅 활용 동의 거부시 이름뒤에 (거부)로 기재해주세요\n\n[해지후 6개월 보유 참고]\n해지 당월 요금은 다음달에 청구해야 하기 때문에 최소 1개월 이상 보관이 필요합니다. 만약 미납이 생기면 그 다음달에도 청구, 또 미납되면 또 그다음달... 이런 식으로 해지후 요금청구에 필요해서 ★최대★ 6개월 보유입니다!\n(예: 4월 해지 → 5월에 요금청구, 미납 시 6월·7월... 최대 10월까지 보유 가능)"},
{id:"cctv_wonestop",carrier:"CCTV",section:"클레임 방어",subsection:"원스톱 해지",ownerTypes:"all",order:1,cctvType:"common",script:"(원스톱해지 가입고객) 원스톱 해지신청으로 해지가능한 기존통신사의 상품은 인터넷과 TV상품에 한하며, 이외 사용하시던 기존상품들은 고객님께서 별도로 해지해주셔야 합니다.\n최초 신청시 정해진 개통일정에서 임의로 설치일정 변경, 기타사유로 인한 설치지연 등으로 설치일정이 변경될 경우 기존 이용하시던 통신사의 상품은 해지접수가 취소될수 있으며, 이경우 고객님께서 직접 해지 신청해주셔야 합니다.",note:null},
{id:"mul001",carrier:"MULTI",section:"녹취통보",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"안녕하세요 인터넷 접수 받은곳인데요 계약내용에 대한 해피콜 안내 진행하겠습니다.",note:null},
{id:"mul002",carrier:"MULTI",section:"기본정보",subsection:"일반",ownerTypes:["일반"],order:1,cctvType:null,script:"XXX님, 명의자 본인 되시구요? (네)\n실명확인차 주민번호 앞자리 6자리 확인 부탁드립니다 (고객님이 불러주셔야됨)\n고객님 성별이 남자or여자분 맞으시죠? (네)",note:null},
{id:"mul003",carrier:"MULTI",section:"기본정보",subsection:"법인/개인사업자",ownerTypes:["법인사업자"],order:1,cctvType:null,script:"(대표자와 녹취) 대표자 000님 본인되시죠? (네)\n(직원과 녹취) 직원이신 000님 본인되시죠? (네)\n\"상호명 00000\", 사업자번호 000-00-00000 명의로 신청하셨죠? (네)",note:null},
{id:"mul004",carrier:"MULTI",section:"상품공통",subsection:"공통",ownerTypes:"all",order:1,cctvType:null,script:"신청하신 상품의 총 요금은 월 000원이며 모두 3년 약정입니다.\n사은품은 00상품권 00만원, 현금사은품은 00만원이고 설치비는 면제해드렸고, 면제된 설치비는 약정내 해지시 위약금으로 청구됩니다.\n현금사은품은 19시 전후로 입금 되십니다.",note:null},
{id:"mul005",carrier:"MULTI",section:"위약금·환수",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"(3년 결합상품이기 때문에) 한가지 상품이라도 중도에 해지하시면 위약금 및 할인반환금이 발생되며, 위약금은 결합할인, 설치비, 장비료 등 사용하시면서 총 할인받으셨던 금액 및 선로투자비용 등입니다.\n(기가류 가입시) 1년 이내 상품 하향시 (상품권 금액이 위약금으로 청구되시고) 결합할인 소멸, 사은품금액 반환 및 새로 설치비 청구되시니 변경없이 이용해주시구요.\n실사용 기준으로 1년이내 해지, 명의변경, 일시정지, 연체, 지로납부로 변경, 복지할인 등록시 위약금과는 별도로 사은품까지 전액 반환하셔야 하니까 최소 1년은 이상없이 사용 부탁드리겠습니다.",note:null},
{id:"mul_log",carrier:"MULTI",section:"클레임 방어",subsection:"물류사은품",ownerTypes:"all",order:91,cctvType:null,script:"(물류사은품) 물류사은품은 수령 이후에는 반송이 불가능하기 때문에 현금으로 반환해 주시면 됩니다.\n초기 불량 확인 전까지 A/S 신청을 위해 제품박스를 버리지 말아주시고, 사은품 불량 사유는 인터넷 해지 사유가 되지 않습니다.",note:"TV상품별 위약금 - 상품권 금액 - 고객 현금부담금액 + 현금사은품 = 물류사은품 위약금"},
{id:"mul006",carrier:"MULTI",section:"클레임 방어",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"★기존에 사용하시던 상품은 자동해지 되지 않으니 직접 해지하셔야합니다. 저랑 통화종료하고 즉시 전통신사에 해지요청 부탁드립니다.★",note:null},
{id:"mul_wonestop",carrier:"MULTI",section:"클레임 방어",subsection:"원스톱 해지",ownerTypes:"all",order:2,cctvType:null,script:"(원스톱해지 가입고객) 원스톱 해지신청으로 해지가능한 기존통신사의 상품은 인터넷과 TV상품에 한하며, 이외 사용하시던 기존상품들은 고객님께서 별도로 해지해주셔야 합니다.\n최초 신청시 정해진 개통일정에서 임의로 설치일정 변경, 기타사유로 인한 설치지연 등으로 설치일정이 변경될 경우 기존 이용하시던 통신사의 상품은 해지접수가 취소될수 있으며, 이경우 고객님께서 직접 해지 신청해주셔야 합니다.",note:null},
{id:"mul007",carrier:"MULTI",section:"개인정보 활용동의",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"서비스제공 등을 위하여 신청인의 성명, 주민번호, 이용시간 및 요금납부자의 성명, 생년월일 등 개인정보를 수집하고 신용정보를 조회하여 가입기간 동안 이용하며 해지후 6개월까지 보유하는데 동의하십니까? (네)\n약정기간 만료, 요금감면 행사 등 마케팅 활용에 동의 하시나요? (네)/(아니요) (Yes를 유도해주세요)",note:"은행권 신용정보가 아니구요 단순 연체 조회입니다~\n동의 하지 않으시면 서비스 제공이 어려우니 동의 부탁드려요\n마케팅 활용 동의 거부시 이름뒤에 (거부)로 기재해주세요\n\n[해지후 6개월 보유 참고]\n해지 당월 요금은 다음달에 청구해야 하기 때문에 최소 1개월 이상 보관이 필요합니다. 만약 미납이 생기면 그 다음달에도 청구, 또 미납되면 또 그다음달... 이런 식으로 해지후 요금청구에 필요해서 ★최대★ 6개월 보유입니다!\n(예: 4월 해지 → 5월에 요금청구, 미납 시 6월·7월... 최대 10월까지 보유 가능)"},
{id:"kt_cctv",carrier:"KT",section:"상품-CCTV",subsection:"기가아이즈",ownerTypes:"all",order:1,cctvType:null,script:"신청하신 상품의 총 요금은 월 000원이며 모두 3년 약정입니다.\n(설치전) CCTV 설치비 00원은 4대까지는 기본적으로 무료이나 기사님 방문시 난공사지역이거나, 천장층고가 3M 이상일때, 사무실 한공간이 아니고 다른공간으로 설치할 때도 청구될 수 있는 점 참고 부탁드립니다.\n사용하시다 이전설치하시게 되면 이전비가 청구되시고, 해지시 철거비가 발생될 수 있습니다.\n(실외형 카메라 있을때) 실외형 카메라는 25M까지만 선공사 무료라 혹시 멀리 떨어져있으면 추가 설치비 부과될 수 있습니다.\nCCTV 상품은 3년약정으로 약정내 해지시 할인반환금 및 CCTV 카메라 장비대여금 반환금이 청구됩니다.\n결합해지, 자사인터넷 해지, 연체, 정지, 명의이전 등 기타 할인프로그램으로 전환, 본사 프로모션 참여시 위약금이 청구될 수 있으며, 설치후 1년 이내 발생되면 추가로 사은품까지 전액 반환하셔야 하니 유의부탁드립니다.\n§※ 면제된 설치비는 약정 내 해지시 위약금으로 청구됩니다.\nKT 기가 인터넷 회선과 결합하여 고화질 영상 저장 및 원격 확인이 가능합니다.\n저장 영상은 30일치 보관되며, 이상 이벤트 발생시 앱으로 알림이 전달됩니다.\n기가아이즈 앱 통해 원격 확인 가능",note:null},
{id:"kt_telecap",carrier:"KT",section:"상품-텔레캅",subsection:"텔레캅",ownerTypes:"all",order:1,cctvType:null,script:"텔레캅은 방문하셔서 계약서 작성하셨고, 텔레캅상품 3년약정으로 약정내 해지시 할인반환금 및 CCTV 카메라 장비대여금 반환금이 청구됩니다.\n결합해지, 자사인터넷 해지, 연체, 정지, 명의이전 등 기타 할인프로그램으로 전환, 본사 프로모션 참여시 위약금이 청구될 수 있으며, 설치후 1년 이내 발생되면 추가로 사은품까지 전액 반환하셔야 하니 유의부탁드립니다.\n§※KT 인터넷 회선과 결합된 서비스입니다. 이상 감지 시 자동으로 고객님께 알림이 전달되며, 실시간 모니터링이 가능합니다.\n기사님이 보고 현장에서 견적나옴 요금,설치비안내x / 고객센터: 080-700-2700",note:null},
{id:"ktb_cctv",carrier:"KT_biz",section:"상품-CCTV",subsection:"기가아이즈",ownerTypes:"all",order:1,cctvType:null,script:"신청하신 상품의 총 요금은 월 000원이며 모두 3년 약정입니다.\n(설치전) CCTV 설치비 00원은 4대까지는 기본적으로 무료이나 기사님 방문시 난공사지역이거나, 천장층고가 3M 이상일때, 사무실 한공간이 아니고 다른공간으로 설치할 때도 청구될 수 있는 점 참고 부탁드립니다.\n사용하시다 이전설치하시게 되면 이전비가 청구되시고, 해지시 철거비가 발생될 수 있습니다.\n(실외형 카메라 있을때) 실외형 카메라는 25M까지만 선공사 무료라 혹시 멀리 떨어져있으면 추가 설치비 부과될 수 있습니다.\nCCTV 상품은 3년약정으로 약정내 해지시 할인반환금 및 CCTV 카메라 장비대여금 반환금이 청구됩니다.\n결합해지, 자사인터넷 해지, 연체, 정지, 명의이전 등 기타 할인프로그램으로 전환, 본사 프로모션 참여시 위약금이 청구될 수 있으며, 설치후 1년 이내 발생되면 추가로 사은품까지 전액 반환하셔야 하니 유의부탁드립니다.\n§※ 면제된 설치비는 약정 내 해지시 위약금으로 청구됩니다.\nKT 기가 인터넷 회선과 결합하여 고화질 영상 저장 및 원격 확인이 가능합니다.\n저장 영상은 30일치 보관되며, 이상 이벤트 발생시 앱으로 알림이 전달됩니다.\n기가아이즈 앱 통해 원격 확인 가능",note:null},
{id:"ktb_telecap",carrier:"KT_biz",section:"상품-텔레캅",subsection:"텔레캅",ownerTypes:"all",order:1,cctvType:null,script:"텔레캅은 방문하셔서 계약서 작성하셨고, 텔레캅상품 3년약정으로 약정내 해지시 할인반환금 및 CCTV 카메라 장비대여금 반환금이 청구됩니다.\n결합해지, 자사인터넷 해지, 연체, 정지, 명의이전 등 기타 할인프로그램으로 전환, 본사 프로모션 참여시 위약금이 청구될 수 있으며, 설치후 1년 이내 발생되면 추가로 사은품까지 전액 반환하셔야 하니 유의부탁드립니다.\n§※KT 인터넷 회선과 결합된 서비스입니다. 이상 감지 시 자동으로 고객님께 알림이 전달되며, 실시간 모니터링이 가능합니다.\n기사님이 보고 현장에서 견적나옴 요금,설치비안내x / 고객센터: 080-700-2700",note:null},
{id:"lg_cctv",carrier:"LG",section:"상품-CCTV",subsection:"CCTV",ownerTypes:"all",order:1,cctvType:null,script:"신청하신 상품의 총 요금은 월 000원이며 모두 3년 약정입니다.\nCCTV 상품은 3년약정으로 약정내 해지시 할인반환금 및 CCTV 카메라 장비대여금 반환금 청구됩니다.\n결합해지, 자사인터넷 해지, 연체, 정지, 명의이전 등 기타 할인프로그램으로 전환, 본사 프로모션 참여시 위약금이 청구될 수 있으며, 설치후 1년 이내 발생되면 추가로 사은품까지 전액 반환하셔야 하니 유의부탁드립니다.\n§※ 장비 판매가 아닌 임대이므로 해지시 통신사로 카메라 반환해야함",note:null},
{id:"lgb_cctv",carrier:"LG_biz",section:"상품-CCTV",subsection:"CCTV",ownerTypes:"all",order:1,cctvType:null,script:"신청하신 상품의 총 요금은 월 000원이며 모두 3년 약정입니다.\nCCTV 상품은 3년약정으로 약정내 해지시 할인반환금 및 CCTV 카메라 장비대여금 반환금 청구됩니다.\n결합해지, 자사인터넷 해지, 연체, 정지, 명의이전 등 기타 할인프로그램으로 전환, 본사 프로모션 참여시 위약금이 청구될 수 있으며, 설치후 1년 이내 발생되면 추가로 사은품까지 전액 반환하셔야 하니 유의부탁드립니다.\n§※ 장비 판매가 아닌 임대이므로 해지시 통신사로 카메라 반환해야함",note:null},
{id:"lgb_usim",carrier:"LG_biz",section:"상품-유심동판",subsection:"유심동판",ownerTypes:"all",order:99,cctvType:null,script:"가입하신 LG휴대폰 00요금제 약정 0년이시고, 0년이내 해지·번호이동·기기변경시 위약금 발생되시구요~\n개통후 단순변심으로인한 취소는 불가하시고, 휴대폰 요금제는 6개월이후 하향가능하시지만\n분실정지·일시정지·미납정지·해지 또는 비정상사용·유심변경·기기변경·가개통·명의변경은 6개월간 불가하시구요.\n6개월이내에는 결합해지도 하시면 안되시고, 안내드린 내용중 한가지라도 위배사항 발생시 지원금 전액환수되시니 주의 부탁드리구요.\n§※ 판매점용 해피콜/ 유심동판 = 인터넷과 함께 LG휴대폰도 동시에 접수된 경우에만 해당",note:null},
{id:"sk_caps",carrier:"SK",section:"상품-캡스",subsection:"캡스",ownerTypes:"all",order:1,cctvType:null,script:"캡스는 방문하셔서 계약서 작성하셨고, 캡스를 해지하시거나 결합된 SK휴대폰은 최소 4개월 결합유지해주셔야하며 이전에 휴대폰 결합이 해지되면 사은품을 돌려주셔야 합니다.\nCCTV 상품은 3년약정으로 약정내 해지시 할인반환금 및 CCTV 카메라 장비대여금 반환금 청구됩니다.\n결합해지, 자사인터넷 해지, 연체, 정지, 명의이전 등 기타 할인프로그램으로 전환, 본사 프로모션 참여시 위약금이 청구될 수 있으며, 설치후 1년 이내 발생되면 추가로 사은품까지 전액 반환하셔야 하니 유의부탁드립니다.\n§※ 장비 판매가 아닌 임대이므로 해지시 통신사로 카메라 반환해야함",note:null},
{id:"skb_caps",carrier:"SK_biz",section:"상품-캡스",subsection:"캡스",ownerTypes:"all",order:1,cctvType:null,script:"캡스는 방문하셔서 계약서 작성하셨고, 캡스를 해지하시거나 결합된 SK휴대폰은 최소 4개월 결합유지해주셔야하며 이전에 휴대폰 결합이 해지되면 사은품을 돌려주셔야 합니다.\nCCTV 상품은 3년약정으로 약정내 해지시 할인반환금 및 CCTV 카메라 장비대여금 반환금 청구됩니다.\n결합해지, 자사인터넷 해지, 연체, 정지, 명의이전 등 기타 할인프로그램으로 전환, 본사 프로모션 참여시 위약금이 청구될 수 있으며, 설치후 1년 이내 발생되면 추가로 사은품까지 전액 반환하셔야 하니 유의부탁드립니다.\n§※ 장비 판매가 아닌 임대이므로 해지시 통신사로 카메라 반환해야함",note:null},
{id:"mob_유심_01",carrier:"MOB_유심",section:"가입유형",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"(신규) (KT,LG,SKT)통신사 신규가입으로 희망하신 전화번호 뒤 4자리는 XXXX 입니다.\n(번호이동) (KT,LG,SKT)통신사에서  (KT,LG,SKT)로 번호이동 신청하셨으며 번호이동 요청하신 전화번호는 010-XXXX-XXXX 입니다.\n(공통) 가입하시는 상품의 약정은 1년or2년이며, 1년or2년이내 해지, 번호이동, 기기변경 시 위약금 발생됩니다.\n(공통) 유심 수령하실 주소지가 xx시 xxx동  xx 호 맞으시죠? (네)",note:null},
{id:"mob_유심_02",carrier:"MOB_유심",section:"상품정보",subsection:"선택약정",ownerTypes:"all",order:2,cctvType:null,script:"월 요금은 선택약정 ㅇㅇㅇ원 할인돼서, 부가세 포함 ㅇㅇㅇ원 청구됩니다.\n(공통) 선택약정 할인은 월정액에서만 25% 할인됩니다.",note:null},
{id:"mob_유심_03",carrier:"MOB_유심",section:"사은품 환수내용",subsection:"단판",ownerTypes:"all",order:3,cctvType:null,script:"( KT M+6개월 ) 간,  OO요금제 유지하시는 조건으로 추가지원금 지원되며,\n6개월 이내 분실정지, 일시정지, 미납정지, 해지, 비정상 사용, 유심변경, 가개통, 명의변경시\n안내받으신 현금사은품 전액 환수 됩니다. 변경 사항이 필요하신 경우 1666-9067 로 연락주시면 변경 가능 일자 확인해드리겠습니다.",note:null},
{id:"mob_유심_04",carrier:"MOB_유심",section:"사은품 환수내용",subsection:"동판",ownerTypes:"all",order:4,cctvType:null,script:"휴대폰 요금제는 개통후 183일 이후 하향 가능하나\n휴대폰 분실정지, 일시정지, 미납정지, 해지, 비정상 사용, 유심변경, 기기변경, 가개통, 명의변경은 6개월간 불가합니다. ☞(SK는 M+6개월 이후 변경 가능)\n인터넷 요금제, TV요금제 하향은 10개월(만 9개월) 이후 가능합니다. 6개월간(KT는 10개월간) 결합 해지 하시면 안되시구요\n위 안내드린 내용 중 한가지라도 위배사항 발생 시 안내받으신 지원금 유선현금OO만원+동판지원금OO만원+무선지원금OO만원\n전액 환수되니 변경 사항이 필요하신 경우 1666-9067 로 연락주시면 변경 가능 일자 확인해드리겠습니다.\n인터넷 설치 불가로 휴대폰만 가입 시엔 유선현금OO원+동판지원금OO원은 지급 불가하며\n휴대폰 개통시 먼저 지원해드린 금액이 있다면, 무선지원금OO만원 제외한 나머지 사은품 전액 환수됩니다.",note:null},
{id:"mob_유심_05",carrier:"MOB_유심",section:"유심 구매시",subsection:null,ownerTypes:"all",order:5,cctvType:null,script:"유심 비용은 첫달 요금 부과시 1회 7,700원 추가로 청구되십니다.",note:null},
{id:"mob_유심_06",carrier:"MOB_유심",section:"개인정보 활용동의",subsection:null,ownerTypes:"all",order:6,cctvType:null,script:"서비스제공 등을 위하여 신청인의 성명, 주민번호, 요금납부자의 성명, 생년월일 등\n개인정보를 수집하고 신용정보를 조회하여 가입기간 동안 이용하며 해지 후 6개월까지 보유하는데 동의하십니까? (네)\n은행권 신용정보가 아니구요, 휴대폰 진행가능여부 확인하는 단순 연체 조회입니다~\n약정기간 만료 , 요금감면 행사등 마케팅 활용에 동의 하시나요? (네)/(아니요) / 동의 하지 않으시면 서비스 제공이 어려우니 동의 부탁드려요\n개인정보 보호에 대한 자세한 내용은 통신사 홈페이지를 참고해 주세요",note:null},
{id:"mob_유심_07",carrier:"MOB_유심",section:"정보조회 안내",subsection:null,ownerTypes:"all",order:7,cctvType:null,script:"저희는 온라인 접수만 도와드리며, 전산으로 정확한 고객님의 정보 조회가 불가합니다.\n현재 사용중인 통신사(이전통신사) 의 잔여할부대금과 위약금이 있는지 고객님께서 직접 확인 해주셔야하며,\n유심 발송 전 간단한 신용정보조회 로 가입 가능여부 확인 후 택배 발송 해드립니다.",note:null},
{id:"mob_유심_08",carrier:"MOB_유심",section:"공통 안내사항",subsection:null,ownerTypes:"all",order:8,cctvType:null,script:"유심 개통 후엔 단순 변심으로 취소 불가합니다. 신중하게 생각후 결정 해주신거 맞으실까요?~ (네)\n유심 수령후 고객님께서 직접 연락주셔야 하며, 3일 이내 연락이 없을 경우 자동으로 휴대폰 개통됩니다.\n불가피한 사정으로 미리 연락을 주신 후 3일 이후 개통을 원하실 경우 신청서 재작성해야하니 참고부탁드립니다.\n가족분들이나. 지인분들 소개시 동일한 혜택 제공도 가능하시며, 고객님께 소개비 3만원 지급가능하시니 많은 소개 부탁드리고\n유심가입해주신 고객님들께 6개월 뒤에 기기변경시 30만원 할인쿠폰 넣어드리고있습니다. 감사합니다^^",note:null},
{id:"mob_유심_09",carrier:"MOB_유심",section:"렌탈 토스",subsection:null,ownerTypes:"all",order:9,cctvType:null,script:"★접수고객 필수멘트★\n저희 가전,정수기,비데 등 렌탈도 좋은 정책으로 가능신데 필요하신 제품 있으신가요?\n지금 전국 최대 사은품이라 상담한번 받아보는거 어떠신가요?",note:null},
{id:"mob_유심_10",carrier:"MOB_유심",section:"사은품",subsection:null,ownerTypes:"all",order:99,cctvType:null,script:"현금사은품은 \"인터넷 사은품 추가지원\"으로만 가능 (필히 인터넷 사은품에서 추가지원이라는 점 안내드리기)",note:null},
{id:"mob_선택_01",carrier:"MOB_선택약정",section:"가입유형",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"(신규) (KT,LG,SKT)통신사 신규가입으로 희망하신 전화번호 뒤 4자리는 XXXX 입니다.\n(기변) (KT,LG,SKT)기기변경 요청하신 전화번호는 010-XXXX-XXX 입니다.\n(번호이동) (KT,LG,SKT)통신사에서  (KT,LG,SKT)로 번호이동 신청하셨으며 번호이동 요청하신 전화번호는 010-XXXX-XXXX 입니다.\n(공통) 가입하시는 상품의 약정은 2년이며, 2년이내 해지, 번호이동, 기기변경시 위약금 발생됩니다.\n(공통) 휴대폰 택배 신청 하신 주소지가 xx시 xxx동  xx 호 맞으시죠? (네)",note:null},
{id:"mob_선택_02",carrier:"MOB_선택약정",section:"상품정보",subsection:"선택약정",ownerTypes:"all",order:2,cctvType:null,script:"(공통)신청하신 모델은 ( 노트20 / 256GB / ㅇㅇ색상 ) 으로 신청 해주셨으며, ㅇㅇㅇ요금제 ( SK M+3개월 / KT 4개월 / LG 3개월) 유지 조건입니다.\n(선납-X) 단말기 출고가는 ㅇㅇㅇ원 이며 할부금, 부가세 포함 월 ㅇㅇㅇ원 청구됩니다.\n(선납-O) 단말기 출고가는 ㅇㅇㅇ원 이며 추가 ㅇㅇㅇ원 할인으로 할부원금 ㅇㅇㅇㅇ원입니다.\n월 요금은 할부ㅇㅇ개월 기준으로, 부가세 포함 ㅇㅇㅇ원 청구됩니다.\n(공통) 단말 할부 구매시 할부에 대한 할부이자 연 5.9% 가 발생됩니다.",note:null},
{id:"mob_선택_03",carrier:"MOB_선택약정",section:"사은품 환수내용",subsection:"단판",ownerTypes:"all",order:3,cctvType:null,script:"( SK M+3개월 / KT 4개월 / LG 3개월 ) 간,  OO요금제 유지하시는 조건으로 추가지원금 지원되며,\n（4 or 6）개월 이내 분실정지, 일시정지, 미납정지, 해지, 비정상 사용, 유심변경, 가개통, 명의변경시\n안내받으신 기기 선납금 or 현금사은품 전액 환수 됩니다. 변경 사항이 필요하신 경우 1666-9067 로 연락주시면 변경가능일자 확인해드리겠습니다.",note:null},
{id:"mob_선택_04",carrier:"MOB_선택약정",section:"사은품 환수내용",subsection:"동판",ownerTypes:"all",order:4,cctvType:null,script:"휴대폰 요금제는 ( SK M+3개월 / KT 4개월 / LG 3개월 ) 개월 이후 하향 가능하나\n휴대폰 분실정지, 일시정지, 미납정지, 해지, 비정상 사용, 유심변경, 기기변경, 가개통, 명의변경은 6개월간 불가합니다. ☞(SK는 M+6개월 이후 변경 가능)\n인터넷 요금제, TV요금제 하향은 10개월(만 9개월) 이후 가능합니다. 6개월간 결합 해지 하시면 안되시구요\n위 안내드린 내용중 한가지라도 위배사항 발생시 안내받으신 지원금 유선현금OO만원+동판지원금OO만원+무선지원금OO만원\n전액 환수 되니 변경 사항이 필요하신 경우 1666-9067 로 연락주시면 변경가능일자 확인해드리겠습니다.\n인터넷 설치 불가로 휴대폰 만 가입시엔 유선현금OO원+동판지원금OO원은 지급 불가하며\n휴대폰 개통시 먼저 지원해드린 금액이 있다면, 무선지원금OO만원 제외 한 나머지 사은품 전액 환수 됩니다.",note:null},
{id:"mob_선택_05",carrier:"MOB_선택약정",section:"유심 구매시",subsection:null,ownerTypes:"all",order:5,cctvType:null,script:"유심 비용은 첫달 요금 부과시 1회 7,700원 추가로 청구되십니다.",note:null},
{id:"mob_선택_06",carrier:"MOB_선택약정",section:"보험",subsection:"보험 가입O",ownerTypes:"all",order:6,cctvType:null,script:"신청하신 보험은 ㅇㅇ이며, 보험료 ㅇㅇ원은 매달 청구가 됩니다. 가입일로부터 36개월간 유지되므로 해지를 원하실땐 직접 해지를 해주셔야 합니다.",note:null},
{id:"mob_선택_07",carrier:"MOB_선택약정",section:"보험",subsection:"보험 가입X",ownerTypes:"all",order:7,cctvType:null,script:"보험은 개통일로부터 30일 이내에만 가입 가능하며 30일 이전에 가입 시 직접 가입을 해주셔야 합니다.",note:null},
{id:"mob_선택_08",carrier:"MOB_선택약정",section:"개인정보 활용동의",subsection:null,ownerTypes:"all",order:8,cctvType:null,script:"서비스제공 등을 위하여 신청인의 성명, 주민번호, 요금납부자의 성명, 생년월일 등\n개인정보를 수집하고 신용정보를 조회하여 가입기간 동안 이용하며 해지후 6개월까지 보유하는데 동의하십니까? (네)\n은행권 신용정보가 아니구요, 휴대폰 진행가능여부 확인하는 단순 연체 조회입니다~\n약정기간 만료 , 요금감면 행사등 마케팅 활용에 동의 하시나요? (네)/(아니요) / 동의 하지 않으시면 서비스 제공이 어려우니 동의 부탁드려요\n개인정보 보호에 대한 자세한 내용은 통신사 홈페이지를 참고해 주세요",note:null},
{id:"mob_선택_10",carrier:"MOB_선택약정",section:"정보조회 안내",subsection:null,ownerTypes:"all",order:10,cctvType:null,script:"저희는 온라인 접수만 도와드리며, 전산으로 정확한 고객님의 정보 조회가 불가합니다.\n현재 사용중인 통신사(이전통신사) 의 잔여할부대금과 위약금이 있는지 고객님께서 직접 확인 해주셔야하며,\n기기 발송 전 간단한 신용정보조회로 할부진행 가능여부, 가입 가능여부 확인 후 택배 발송 해드립니다.",note:null},
{id:"mob_선택_11",carrier:"MOB_선택약정",section:"공통 안내사항",subsection:"선개통 고객",ownerTypes:"all",order:11,cctvType:null,script:"안내드린 가입조건으로 개통 도와드리기 위해 기기 발송 전 안내드린 가입 조건으로 선개통 후 기기 발송 도와드리며,\n금일 발송 전 개통 후엔 단순 변심으로 색상, 모델 등의 사유로는 취소 및 교환 불가합니다.\n신중하게 생각후 결정 해주신거 맞으실까요?~ (네)\n기기 초기 불량시 개통후 14일 이내에 서비스센터 가야하니 참고해주시구요~\n가족분들이나. 지인분들 소개시 동일한 혜택 제공도 가능하시며, 고객님께 소개비 3만원 지급가능하시니 많은 소개 부탁드리겠습니다^^ 감사합니다.",note:null},
{id:"mob_선택_12",carrier:"MOB_선택약정",section:"공통 안내사항",subsection:"후개통 고객",ownerTypes:"all",order:12,cctvType:null,script:"기기 개통 전 휴대폰 개봉 절대 불가하며, 개통 후 개봉 가능합니다.\n기기 수령후 고객님께서 직접 연락주셔야 하며, 3일 이내 연락이 없을 경우 자동으로 휴대폰 개통됩니다.\n불가피한 사정으로 미리 연락을 주신 후 3일 이후 개통을 원하실 경우 신청서 재작성해야하니 참고부탁드립니다.\n현재 사용중인 휴대폰 기기 수령전까지 사용하시기 위해 받아 보신 후 개통 도와드리지만,\n정책 하향 및 공시지원금 하향시 안내드린 금액 변동 있을 수 있으니, 기기 수령후 바로 개통 요청 주셔야합니다.\n기기 개통 및 개봉 시 단순변심으로 색상, 모델 등의 사유로는 취소 및 교환 불가하며,\n기기 초기 불량시 개통후 14일 이내에 서비스센터 가야하니 참고해주세요.\n가족분들이나. 지인분들 소개시 동일한 혜택 제공도 가능하시며, 고객님께 소개비 3만원 지급가능하시니 많은 소개 부탁드리겠습니다^^ 감사합니다.",note:null},
{id:"mob_선택_13",carrier:"MOB_선택약정",section:"렌탈 토스",subsection:null,ownerTypes:"all",order:13,cctvType:null,script:"★접수고객 필수멘트★\n저희 가전,정수기,비데 등 렌탈도 좋은 정책으로 가능신데 필요하신 제품 있으신가요?\n지금 전국 최대 사은품이라 상담한번 받아보는거 어떠신가요?",note:null},
{id:"mob_선택_14",carrier:"MOB_선택약정",section:"사은품",subsection:null,ownerTypes:"all",order:99,cctvType:null,script:"현금사은품은 \"인터넷 사은품 추가지원\"으로만 가능 (필히 인터넷 사은품에서 추가지원이라는 점 안내드리기)",note:null},
{id:"mob_공시_01",carrier:"MOB_공시지원금",section:"가입유형",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"(신규) (KT,LG,SKT)통신사 신규가입으로 희망하신 전화번호 뒤 4자리는 XXXX 입니다.\n(기변) (KT,LG,SKT)기기변경 요청하신 전화번호는 010-XXXX-XXX 입니다.\n(번호이동) (KT,LG,SKT)통신사에서  (KT,LG,SKT)로 번호이동 신청하셨으며 번호이동 요청하신 전화번호는 010-XXXX-XXXX 입니다.\n(공통) 가입하시는 상품의 약정은 2년이며, 2년이내 해지, 번호이동, 기기변경시 위약금 발생됩니다.\n(공통) 휴대폰 택배 신청 하신 주소지가 xx시 xxx동  xx 호 맞으시죠? (네)",note:null},
{id:"mob_공시_02",carrier:"MOB_공시지원금",section:"상품정보",subsection:"공시지원",ownerTypes:"all",order:2,cctvType:null,script:"(공통) 신청하신 모델은 ( 노트20 / 256GB / ㅇㅇ색상 ) 으로 신청 해주셨으며, ㅇㅇㅇ요금제 6개월 유지 조건입니다.\n(선납-X) 단말기 출고가 ㅇㅇㅇ원에서  공시지원금 ㅇㅇㅇ원 할인되어 할부원금 ㅇㅇㅇ원 입니다.\n(선납-O) 단말기 출고가 ㅇㅇㅇ원에서  공시지원금 ㅇㅇㅇ 이며 추가 ㅇㅇㅇ원 할인으로 할부원금 ㅇㅇㅇㅇ원입니다.\n월 요금은 할부ㅇㅇ개월 기준으로, 부가세 포함 ㅇㅇㅇ원 청구됩니다.\n(공통) 단말 할부 구매시 할부에 대한 할부이자 연 5.9% 가 발생됩니다.",note:null},
{id:"mob_공시_03",carrier:"MOB_공시지원금",section:"사은품 환수내용",subsection:"단판",ownerTypes:"all",order:3,cctvType:null,script:"６개월간,  OO요금제 유지하시는 조건으로 추가지원금 지원되며,\n６개월 이내 분실정지, 일시정지, 미납정지, 해지, 비정상 사용, 유심변경, 가개통, 명의변경시\n안내받으신 기기 선납금 or 현금사은품 전액 환수 됩니다. 변경 사항이 필요하신 경우 1666-9067 로 연락주시면 변경가능일자 확인해드리겠습니다.",note:null},
{id:"mob_공시_04",carrier:"MOB_공시지원금",section:"사은품 환수내용",subsection:"동판",ownerTypes:"all",order:4,cctvType:null,script:"휴대폰 요금제는 6개월 이후 하향 가능하나 (skt42/ kt47/ lg45) 요금제까지만 하향 가능합니다\n휴대폰 분실정지, 일시정지, 미납정지, 해지, 비정상 사용, 유심변경, 기기변경, 가개통, 명의변경은 6개월간 불가합니다. ☞(SK는 M+6개월 이후 변경 가능)\n인터넷 요금제, TV요금제 하향은 10개월(만 9개월) 이후 가능합니다. 6개월간 결합 해지 하시면 안되시구요\n위 안내드린 내용중 한가지라도 위배사항 발생시 안내받으신 지원금 유선현금OO만원+동판지원금OO만원+무선지원금OO만원\n전액 환수 되니 변경 사항이 필요하신 경우 1666-9067 로 연락주시면 변경가능일자 확인해드리겠습니다.\n인터넷 설치 불가로 휴대폰 만 가입시엔 유선현금OO원+동판지원금OO원은 지급 불가하며\n휴대폰 개통시 먼저 지원해드린 금액이 있다면, 무선지원금OO만원 제외 한 나머지 사은품 전액 환수 됩니다.",note:null},
{id:"mob_공시_05",carrier:"MOB_공시지원금",section:"유심 구매시",subsection:null,ownerTypes:"all",order:5,cctvType:null,script:"유심 비용은 첫달 요금 부과시 1회 7,700원 추가로 청구되십니다.",note:null},
{id:"mob_공시_06",carrier:"MOB_공시지원금",section:"보험",subsection:"보험 가입O",ownerTypes:"all",order:6,cctvType:null,script:"신청하신 보험은 ㅇㅇ이며, 보험료 ㅇㅇ원은 매달 청구가 됩니다. 가입일로부터 36개월간 유지되므로 해지를 원하실땐 직접 해지를 해주셔야 합니다.",note:null},
{id:"mob_공시_07",carrier:"MOB_공시지원금",section:"보험",subsection:"보험 가입X",ownerTypes:"all",order:7,cctvType:null,script:"보험은 개통일로부터 30일 이내에만 가입 가능하며 30일 이전에 가입 시 직접 가입을 해주셔야 합니다.",note:null},
{id:"mob_공시_08",carrier:"MOB_공시지원금",section:"개인정보 활용동의",subsection:null,ownerTypes:"all",order:8,cctvType:null,script:"서비스제공 등을 위하여 신청인의 성명, 주민번호, 요금납부자의 성명, 생년월일 등\n개인정보를 수집하고 신용정보를 조회하여 가입기간 동안 이용하며 해지후 6개월까지 보유하는데 동의하십니까? (네)\n은행권 신용정보가 아니구요, 휴대폰 진행가능여부 확인하는 단순 연체 조회입니다~\n약정기간 만료 , 요금감면 행사등 마케팅 활용에 동의 하시나요? (네)/(아니요) / 동의 하지 않으시면 서비스 제공이 어려우니 동의 부탁드려요\n개인정보 보호에 대한 자세한 내용은 통신사 홈페이지를 참고해 주세요",note:null},
{id:"mob_공시_10",carrier:"MOB_공시지원금",section:"정보조회 안내",subsection:null,ownerTypes:"all",order:10,cctvType:null,script:"저희는 온라인 접수만 도와드리며, 전산으로 정확한 고객님의 정보 조회가 불가합니다.\n현재 사용중인 통신사(이전통신사) 의 잔여할부대금과 위약금이 있는지 고객님께서 직접 확인 해주셔야하며,\n기기 발송 전 간단한 신용정보조회로 할부진행 가능여부, 가입 가능여부 확인 후 택배 발송 해드립니다.",note:null},
{id:"mob_공시_11",carrier:"MOB_공시지원금",section:"공통 안내사항",subsection:"선개통 고객",ownerTypes:"all",order:11,cctvType:null,script:"안내드린 가입조건으로 개통 도와드리기 위해 기기 발송 전 안내드린 가입 조건으로 선개통 후 기기 발송 도와드리며,\n금일 발송 전 개통 후엔 단순 변심으로 색상, 모델 등의 사유로는 취소 및 교환 불가합니다.\n신중하게 생각후 결정 해주신거 맞으실까요?~ (네)\n기기 초기 불량시 개통후 14일 이내에 서비스센터 가야하니 참고해주시구요~\n가족분들이나. 지인분들 소개시 동일한 혜택 제공도 가능하시며, 고객님께 소개비 3만원 지급가능하시니 많은 소개 부탁드리겠습니다^^ 감사합니다.",note:null},
{id:"mob_공시_12",carrier:"MOB_공시지원금",section:"공통 안내사항",subsection:"후개통 고객",ownerTypes:"all",order:12,cctvType:null,script:"기기 개통 전 휴대폰 개봉 절대 불가하며, 개통 후 개봉 가능합니다.\n기기 수령후 고객님께서 직접 연락주셔야 하며, 3일 이내 연락이 없을 경우 자동으로 휴대폰 개통됩니다.\n불가피한 사정으로 미리 연락을 주신 후 3일 이후 개통을 원하실 경우 신청서 재작성해야하니 참고부탁드립니다.\n현재 사용중인 휴대폰 기기 수령전까지 사용하시기 위해 받아 보신 후 개통 도와드리지만,\n정책 하향 및 공시지원금 하향시 안내드린 금액 변동 있을 수 있으니, 기기 수령후 바로 개통 요청 주셔야합니다.\n기기 개통 및 개봉 시 단순변심으로 색상, 모델 등의 사유로는 취소 및 교환 불가하며,\n기기 초기 불량시 개통후 14일 이내에 서비스센터 가야하니 참고해주세요.\n가족분들이나. 지인분들 소개시 동일한 혜택 제공도 가능하시며, 고객님께 소개비 3만원 지급가능하시니 많은 소개 부탁드리겠습니다^^ 감사합니다.",note:null},
{id:"mob_공시_13",carrier:"MOB_공시지원금",section:"렌탈 토스",subsection:null,ownerTypes:"all",order:13,cctvType:null,script:"★접수고객 필수멘트★\n저희 가전,정수기,비데 등 렌탈도 좋은 정책으로 가능신데 필요하신 제품 있으신가요?\n지금 전국 최대 사은품이라 상담한번 받아보는거 어떠신가요?",note:null},
{id:"mob_공시_14",carrier:"MOB_공시지원금",section:"사은품",subsection:null,ownerTypes:"all",order:99,cctvType:null,script:"현금사은품은 \"인터넷 사은품 추가지원\"으로만 가능 (필히 인터넷 사은품에서 추가지원이라는 점 안내드리기)",note:null}
,
{id:"wisely_001",carrier:"WISELY",section:"해피콜안내",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"마지막으로, 가입내용 정리 및 필수 안내사항 해피콜 녹취를 짧게 진행하겠습니다.\n본 계약은 비대면으로 진행되며, 모든 가입 내용은 해피콜 녹취로 계약 증빙되니 참고 부탁드립니다.",note:null},
{id:"wisely_002",carrier:"WISELY",section:"가입내용 정리",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"신청하신 상품은 [KT / SK / LG] [인터넷 000M + TV ㅇㅇㅇ + WIFI]이며,\n요금은 부가세 포함 ㅇㅇㅇ원이시구요, 약정은 3년입니다.\n사은품은 (ㅇㅇ모바일상품권 ㅇ만원) + 법정지원금(현금) ㅇㅇ만원 + 와이즐리 포인트 000이고,\n후기 리워드(포인트)는 개통일로부터 1년 이내 작성시에만 지급됩니다.\n설치비는 000원이며, 평일 외 시간·주말·공휴일 설치 시에는 할증이 발생하니 참고 부탁드립니다.",note:null},
{id:"wisely_003",carrier:"WISELY",section:"상품변경,결합변경,할인등록,위약금 및 환수",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"1년 이내 한 가지 상품이라도 중도 해지하거나, 셋탑 또는 요금제 하향, 결합해지,\n미지원 복지할인 등록, 연체, 정지, 명의이전, 패밀리 결합, 기타 할인프로그램 등록,\n기업용 상품과의 결합 또는 전환 시 위약금이 발생할 수 있고 사은품까지 전액 반환되니 유의 부탁드리구요.",note:null},
{id:"wisely_004",carrier:"WISELY",section:"음성적 재가입",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"신청하신 통신사의 인터넷 상품 신규 개통일 기준으로, 설치 장소·사용명의와 관계없이\n설치 전 해지한 동일 통신사 회선이 확인될 경우, 또는 설치 후 1년 이내 동일 통신사 회선의 해지·정지가 확인될 경우,\n신규 개통 시 지급받으신 모든 사은품이 반환될 수 있습니다.\n다만, 본사에 소명 요청이 가능할 경우에는 등본이나 임대차계약서 등의 추가서류가 필요할 수 있습니다.",note:null},
{id:"wisely_005",carrier:"WISELY",section:"마무리",subsection:null,ownerTypes:"all",order:1,cctvType:null,script:"해피콜 녹취 완료되셨구요, 바로 접수 진행 도와드리겠습니다. 감사합니다.",note:null}];
}

function resetSheet() {
  const sheet = getOrCreateSheet();
  const lastRow = sheet.getLastRow();
  if (lastRow > 1) sheet.getRange(2, 1, lastRow - 1, 9).clearContent();
  const defaults = getDefaultData();
  saveScripts(JSON.stringify(defaults));
  Logger.log('✅ 시트 초기화 완료! ' + defaults.length + '개 항목 업로드됐습니다.');
}
